#!/usr/bin/env node
/**
 * KEFE Design Tokens — Build Script
 *
 * Reads tokens.json and generates:
 * - dist/tokens.css     — CSS custom properties for dark and light themes
 * - dist/index.mjs      — ESM export of the raw token object
 * - dist/index.js       — CJS export of the raw token object
 * - dist/index.d.ts     — TypeScript types
 *
 * Usage:
 *   node scripts/build.mjs
 *   # or via npm: npm run build
 */

import { readFileSync, mkdirSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = join(__dirname, "..");
const DIST = join(ROOT, "dist");
const tokensPath = join(ROOT, "tokens.json");

const tokens = JSON.parse(readFileSync(tokensPath, "utf-8"));

mkdirSync(DIST, { recursive: true });

// ---------------------------------------------------------------------------
// CSS custom properties
// ---------------------------------------------------------------------------

function hexToRgb(hex) {
  // Strip # prefix
  const h = hex.replace(/^#/, "");
  if (h.length === 3 || h.length === 4) {
    const r = parseInt(h[0] + h[0], 16);
    const g = parseInt(h[1] + h[1], 16);
    const b = parseInt(h[2] + h[2], 16);
    return `${r} ${g} ${b}`;
  }
  if (h.length >= 6) {
    const r = parseInt(h.slice(0, 2), 16);
    const g = parseInt(h.slice(2, 4), 16);
    const b = parseInt(h.slice(4, 6), 16);
    return `${r} ${g} ${b}`;
  }
  return null;
}

function colorTokensToCss(themeTokens, prefix) {
  const lines = [];
  for (const [name, token] of Object.entries(themeTokens)) {
    if (!token?.value) continue;
    const varName = `--kefe-color-${name.replace(/_/g, "-")}`;
    lines.push(`  ${varName}: ${token.value};`);
    // Also expose as RGB channel split for alpha compositing
    const rgb = hexToRgb(token.value);
    if (rgb) {
      lines.push(`  ${varName}-rgb: ${rgb};`);
    }
  }
  return lines.join("\n");
}

function spacingTokensToCss(spacingTokens) {
  return Object.entries(spacingTokens)
    .filter(([, t]) => t?.value)
    .map(([key, token]) => `  --kefe-spacing-${key}: ${token.value};`)
    .join("\n");
}

function radiusTokensToCss(radiusTokens) {
  return Object.entries(radiusTokens)
    .filter(([, t]) => t?.value)
    .map(([key, token]) => `  --kefe-radius-${key}: ${token.value};`)
    .join("\n");
}

function shadowTokensToCss(shadowTokens) {
  return Object.entries(shadowTokens)
    .filter(([, t]) => t?.value)
    .map(([key, token]) => `  --kefe-shadow-${key.replace(/_/g, "-")}: ${token.value};`)
    .join("\n");
}

function motionTokensToCss(motionTokens) {
  const lines = [];
  for (const [group, value] of Object.entries(motionTokens)) {
    if (typeof value !== "object" || value === null) continue;
    if (value.value) {
      lines.push(`  --kefe-motion-${group}: ${value.value};`);
      continue;
    }
    for (const [key, token] of Object.entries(value)) {
      if (token?.value) {
        lines.push(`  --kefe-motion-${group}-${key.replace(/_/g, "-")}: ${token.value};`);
      }
    }
  }
  return lines.join("\n");
}

function signalTokensToCss(signalTokens) {
  const lines = [];
  for (const [group, value] of Object.entries(signalTokens)) {
    if (typeof value !== "object" || value === null) continue;
    for (const [key, token] of Object.entries(value)) {
      if (token?.value) {
        lines.push(`  --kefe-signal-${group}-${key.replace(/_/g, "-")}: ${token.value};`);
      }
    }
  }
  return lines.join("\n");
}

const darkCss = colorTokensToCss(tokens.color?.dark ?? {}, "dark");
const lightCss = colorTokensToCss(tokens.color?.light ?? {}, "light");
const spacingCss = spacingTokensToCss(tokens.spacing ?? {});
const radiusCss = radiusTokensToCss(tokens.border_radius ?? tokens.radius ?? {});
const shadowCss = shadowTokensToCss(tokens.shadow ?? {});
const motionCss = motionTokensToCss(tokens.motion ?? {});
const signalCss = signalTokensToCss(tokens.signal ?? {});

const css = `/**
 * KEFE Design Tokens — Generated CSS custom properties
 * DO NOT EDIT — generated by packages/kefe-design-tokens/scripts/build.mjs
 * Source: tokens.json v${tokens.$metadata?.version ?? "1.0.0"}
 */

/* Dark theme (default) */
:root,
[data-theme="dark"] {
${darkCss}
${spacingCss}
${radiusCss}
${shadowCss}
${motionCss}
${signalCss}
}

/* Light theme */
[data-theme="light"] {
${lightCss}
}

/* Reduced-motion override */
@media (prefers-reduced-motion: reduce) {
  :root {
    --kefe-motion-duration-instant: 0ms;
    --kefe-motion-duration-fast: 0ms;
    --kefe-motion-duration-normal: 0ms;
    --kefe-motion-duration-slow: 0ms;
    --kefe-motion-duration-deliberate: 0ms;
  }
}
`;

writeFileSync(join(DIST, "tokens.css"), css, "utf-8");

// ---------------------------------------------------------------------------
// ESM + CJS exports
// ---------------------------------------------------------------------------

const esmContent = `// KEFE Design Tokens — ESM
// Generated by packages/kefe-design-tokens/scripts/build.mjs
export const tokens = ${JSON.stringify(tokens, null, 2)};
export default tokens;
`;

const cjsContent = `// KEFE Design Tokens — CJS
// Generated by packages/kefe-design-tokens/scripts/build.mjs
const tokens = ${JSON.stringify(tokens, null, 2)};
module.exports = { tokens };
module.exports.default = tokens;
`;

writeFileSync(join(DIST, "index.mjs"), esmContent, "utf-8");
writeFileSync(join(DIST, "index.js"), cjsContent, "utf-8");

// ---------------------------------------------------------------------------
// TypeScript declarations
// ---------------------------------------------------------------------------

const dts = `// KEFE Design Tokens — TypeScript declarations
// Generated by packages/kefe-design-tokens/scripts/build.mjs

export interface DesignToken {
  value: string;
  type: string;
  description?: string;
}

export interface ColorTheme {
  canvas: DesignToken;
  surface: DesignToken;
  raised: DesignToken;
  sunken: DesignToken;
  foreground: DesignToken;
  muted: DesignToken;
  gold: DesignToken;
  gold_subtle: DesignToken;
  rules_cyan: DesignToken;
  empathy_coral: DesignToken;
  burgundy: DesignToken;
  success: DesignToken;
  attention: DesignToken;
  critical: DesignToken;
  overlay: DesignToken;
  [key: string]: DesignToken;
}

export interface KefeTierTokens {
  gold_standard: DesignToken;
  silver_validated: DesignToken;
  bronze_observed: DesignToken;
  unqualified: DesignToken;
}

export interface KefeTokens {
  $metadata: {
    version: string;
    authority: string;
    generated_at: string;
    note: string;
  };
  color: {
    dark: ColorTheme;
    light: ColorTheme;
  };
  typography: Record<string, Record<string, DesignToken>>;
  spacing: Record<string, DesignToken>;
  border_radius: Record<string, DesignToken>;
  shadow: Record<string, DesignToken>;
  motion: Record<string, Record<string, DesignToken | string>>;
  signal: {
    tier: KefeTierTokens;
  };
}

export declare const tokens: KefeTokens;
export default tokens;
`;

writeFileSync(join(DIST, "index.d.ts"), dts, "utf-8");

console.log("✓  KEFE design tokens built successfully.");
console.log(`   dist/tokens.css (${css.length} bytes)`);
console.log(`   dist/index.mjs + index.js + index.d.ts`);