import 'kefe_locale_catalog.dart';

abstract final class InternalAlphaStringCatalog {
  static const KefeLocaleResources resources = {
    'en': {
      'primary_nav.explore': 'Explore',
      'primary_nav.weigh': 'Weigh',
      'primary_nav.activity': 'Activity',
      'primary_nav.my_kefe': 'My KEFE',
      'account.title': 'Protect your history',
      'account.heading': 'Keep your weighs with you.',
      'account.body':
          'An account is optional. You can stay a guest; converting preserves your existing server history under the same identity.',
      'account.email': 'Email',
      'account.phone': 'Phone',
      'account.email_address': 'Email address',
      'account.phone_number': 'Phone number',
      'account.send_code': 'Send verification code',
      'account.code_instruction':
          'Enter the 6-digit code sent to {destination}.',
      'account.verification_code': 'Verification code',
      'account.convert': 'Convert account',
      'account.merged':
          'Account verified and both histories were safely merged.',
      'account.preserved':
          'Account verified. Your existing weigh history is preserved.',
      'account.return_my_kefe': 'Return to My KEFE',
      'account.protect_action': 'Protect my history',
      'account.failure': 'Could not complete · {code}',
      'account.error_otp_invalid':
          'The verification code is incorrect. Please check the code and try again.',
      'account.error_otp_expired':
          'The verification code has expired. Please request a new code.',
      'account.error_otp_locked':
          'Too many verification attempts. Please try again later or request a new code.',
      'account.error_challenge_expired':
          'The verification session has expired. Please request a new code.',
      'account.error_merge_failed':
          'Could not merge your account history. Please request a new verification code.',
      'account.error_delivery_unavailable':
          'Verification code delivery is temporarily unavailable. Please try again later.',
      'account.error_generic':
          'Verification could not be completed. Please try again.',
      'account.restart_challenge': 'Change destination or request new code',
      'activity.eyebrow': 'ACTIVITY',
      'activity.title': 'Return to your decisions.',
      'activity.subtitle':
          'Saved Cases, past decisions and revisit history stay distinct here.',
      'activity.loading': 'Loading your activity…',
      'activity.unavailable': 'Activity is currently unavailable.',
      'activity.retry': 'Retry',
      'activity.empty':
          'You have no past weighs yet. They will appear after your first decision.',
      'activity.history_title': 'Decision history',
      'activity.committed': 'Decision committed',
      'activity.reflected': 'Reflection completed',
      'activity.update_count.one': '{count} decision update',
      'activity.update_count.many': '{count} decision updates',
      'activity.preview_notice':
          'Decision history on this screen is Product Preview sample data, not live user data.',
      'weigh_hub.eyebrow': 'WEIGH',
      'weigh_hub.title': 'Choose your next decision.',
      'weigh_hub.subtitle':
          'Decide first; collective results unlock only after Commit.',
      'weigh_hub.recommended': 'RECOMMENDED WEIGH',
      'weigh_hub.start': 'Start weighing',
      'weigh_hub.more': 'More Cases',
      'weigh_hub.empty': 'No Cases are currently open for weighing.',
      'privacy.title': 'Privacy and data',
      'privacy.heading': 'Your data and privacy',
      'privacy.body':
          'Export a machine-readable copy of your product history or delete private data attached to your account/guest identity.',
      'privacy.export_ready': 'Your data copy is ready',
      'privacy.export_copied':
          'Machine-readable JSON was copied to the clipboard. Security tokens and other users’ data are excluded.',
      'privacy.export_summary_title': 'Included in this copy',
      'privacy.export_record_count.one': '{count} record included',
      'privacy.export_record_count.many': '{count} records included',
      'privacy.export_group_count.one': '1 data group contains records',
      'privacy.export_group_count.many': '{count} data groups contain records',
      'privacy.done': 'Done',
      'privacy.export': 'Export my data',
      'privacy.delete': 'Delete my data',
      'privacy.failure': 'Privacy action failed · {code}',
      'privacy.delete_title': 'Delete data permanently?',
      'privacy.delete_body': 'This cannot be undone. Type DELETE to continue.',
      'privacy.cancel': 'Cancel',
      'privacy.delete_permanently': 'Delete permanently',
      'privacy.delete_complete_title': 'Your data has been deleted',
      'privacy.delete_complete_body':
          'Private product data linked to this identity was deleted. Aggregate contributions were anonymized.',
      'privacy.delete_preview_complete_title': 'Preview data reset',
      'privacy.delete_preview_complete_body':
          'Product Preview sample data was reset. No production account or live data was deleted.',
      'privacy.delete_continue': 'Continue',
      'share.title': 'Share this case',
      'share.case_only_note':
          'MVP sharing is case-only. Your decision, confidence, and private reason are never included in the link.',
      'share.preparing': 'Preparing link…',
      'share.create': 'Create case link',
      'share.copied': 'Link copied.',
      'share.copy': 'Copy',
      'share.revoke': 'Revoke link',
      'share.failure': 'Share failed · {code}',
      'public_share.unavailable': 'This share is no longer available.',
      'public_share.retry': 'Try again',
      'public_share.eyebrow': 'A KEFE case was shared',
      'public_share.blind_first':
          "The sender’s decision is never shown here. Weigh the same case and Commit first; collective results unlock only after your own Commit.",
      'public_share.weigh': 'Weigh it myself',
      'community.title': 'Community reasons',
      'community.private_note':
          'Your private reason is never published here automatically. Community contribution is a separate action; text contributions are moderated.',
      'community.publish_heading': 'Publish a separate reason',
      'community.optional_text': 'Optional short text',
      'community.moderation_note':
          'Text waits for moderation before public display.',
      'community.submitting': 'Submitting…',
      'community.publish': 'Publish to community',
      'community.receipt_pending':
          'Contribution received. Text may become visible after moderation.',
      'community.receipt_allowed':
          'Your contribution was added to Community Reasons.',
      'community.unavailable': 'Community data unavailable · {code}',
      'community.patterns_eyebrow': 'DESCRIPTIVE PATTERNS',
      'community.patterns_title': 'What shaped the published reasons',
      'community.patterns_sample': 'Across {count} published reasons',
      'community.patterns_value': '{count} / {sample}',
      'community.patterns_semantics':
          '{label}: {count} of {sample} published reasons',
      'community.patterns_note':
          'One contribution can carry several tags, so rows do not add up to 100%. This is descriptive—not a popularity or truth ranking.',
      'community.published': 'Published reasons',
      'community.resonates': 'Resonates',
      'community.useful': 'Useful',
      'community.report': 'Report',
      'consensus.loading': 'Preparing consensus card…',
      'consensus.commit_first': 'Commit your decision first',
      'consensus.commit_first_body':
          'Consensus participation unlocks only after a completed weigh.',
      'consensus.retry': 'Retry',
      'consensus.exposed': 'EXPOSED · Not part of the core result sample',
      'consensus.prompt':
          'How much do you agree? This card’s distribution unlocks after your own response.',
      'consensus.reason_limit': 'Choose up to {max} reason tags',
      'consensus.submitting': 'Submitting…',
      'consensus.join': 'Join the consensus',
      'consensus.exposed_methodology':
          'Because this happens after your decision, it is stored as EXPOSED. It is not the core result or a Signal.',
      'consensus.distribution': 'CONSENSUS DISTRIBUTION',
      'consensus.reason_patterns': 'REASON PATTERNS',
      'consensus.eyebrow': 'WE · COMMON GROUND',
      'consensus.card_title': 'Consensus Card',
      'consensus.unavailable': 'Consensus temporarily unavailable',
      'consensus.unavailable_with_code':
          'Consensus temporarily unavailable · {code}',
      'consensus.stance.agree': 'Agree',
      'consensus.stance.mixed': 'Mixed',
      'consensus.stance.disagree': 'Disagree',
      'consensus.reason.fairness': 'Fairness',
      'consensus.reason.need': 'Need',
      'consensus.reason.rules': 'Rules',
      'consensus.reason.practical_impact': 'Practical impact',
      'consensus.reason.responsibility': 'Responsibility',
      'domain.daily_life': 'Daily life',
      'domain.technology': 'Technology',
      'domain.sports': 'Sports',
      'domain.civic': 'Civic',
      'domain.work_economy': 'Work & Economy',
      'domain.education': 'Education',
      'domain.family_parenting': 'Family & Parenting',
      'domain.culture_media': 'Culture & Media',
      'context.event_summary': 'Event summary',
      'context.information_status': 'Information status',
      'journey.label': 'DECISION JOURNEY',
      'step.case': 'Case',
      'step.weigh': 'Weigh',
      'step.result': 'Result',
      'step.reflection': 'Reflection',
      'step.completed': 'Completed',
      'result.eyebrow': 'RESULTS',
      'result.your_decision': 'YOUR DECISION',
      'result.community_distribution': 'COMMUNITY DISTRIBUTION',
      'result.kefe_gap': 'KEFE GAP',
      'result.gap.top':
          'Your choice has the largest share in the community. {percent}% of participants chose the same option.',
      'result.gap.not_top':
          'Your choice is not the community majority. {percent}% of participants chose the same option.',
      'result.gap.difference':
          'Your choice has {selectedPercent}% of the community. The gap to the leading option is {gapPoints} percentage points.',
      'result.decision_you': 'You',
      'result.balance_no_selection': 'No selection yet',
      'result.balance_semantics': 'KEFE balance. {selectedLabel}',
      'result.methodology': '{trustedSample} · n={sampleSize} · {confidence}',
      'confidence.high': 'High confidence',
      'confidence.medium': 'Medium confidence',
      'confidence.low': 'Low confidence',
      'perspective.eyebrow': 'COUNTER VIEWS',
      'question.confidence': 'CONFIDENCE',
      'question.decision': 'DECISION',
      'decision.opt_out_insufficient_info': 'Not enough information / Don’t know',
      'decision.opt_out_missing_options': 'Options are missing / Incomplete choices',
      'decision.opt_out_title': 'ALTERNATIVE RESPONSES',
      'reasons.eyebrow': 'REASONS',
      'alpha.acadPortCorpGraph': 'Argument Graph',
      'alpha.acadPortEyebrow': 'ACADEMIC RESEARCH',
      'alpha.accVoiceEyebrow': 'ACCESSIBLE VOICE',
      'alpha.accVoiceModeDictation': 'Anonymized Voice',
      'alpha.actionEvidenceButton': 'View Evidence',
      'alpha.actionEyebrow': 'ACTION',
      'alpha.actionProgressLabel': '{pct}% Progress',
      'alpha.actionStatusInProgress': 'Progress',
      'alpha.actionStatusProposed': 'Proposed',
      'alpha.actionStatusStalled': 'Stalled',
      'alpha.actionStatusVerifiedComplete': 'Verified Complete',
      'alpha.actionTargetDate': 'Target: {date}',
      'alpha.actionTrackEyebrow': 'INSTITUTION ACTION',
      'alpha.actionTrackStatusProgress': 'In Progress',
      'alpha.agendaThrEyebrow': 'DYNAMIC CIVIC AGENDA',
      'alpha.agendaThrTierNational': 'National Urgency',
      'alpha.aiAuditEyebrow': 'AI HALLUCINATION',
      'alpha.aiAuditStGrounded': 'Factually Grounded',
      'alpha.aiFacEyebrow': 'NEUTRALITY-GUARANTEED',
      'alpha.aiFacModeSocratic': 'Socratic Inquiry',
      'alpha.anatomyDriverNormative': 'Moral',
      'alpha.anatomyEyebrow': 'ANATOMY',
      'alpha.appealPanelEyebrow': 'COMMUNITY APPEALS',
      'alpha.appealPanelVerdictOverturned': 'Overturned',
      'alpha.argClusteringArchetypeAlternative': 'Alternative Paradigm',
      'alpha.argClusteringArchetypeBridge': 'Bridge Synthesis',
      'alpha.argClusteringArchetypeNearConsensus': 'Near-Consensus',
      'alpha.argClusteringArchetypeOpposing': 'Opposing Principle',
      'alpha.argClusteringEyebrow': 'ARGUMENT PATTERN',
      'alpha.argClusteringTotalArgs': '{total} Arguments Clustered',
      'alpha.argStrengthEyebrow': 'ARGUMENT STRENGTH',
      'alpha.argStrengthTierRobust': 'Tier A',
      'alpha.blindEyebrow': 'BLIND-FIRST',
      'alpha.blindModeActor': 'Actor Blind',
      'alpha.botShieldEyebrow': 'SYNTHETIC ASTROTURFING',
      'alpha.botShieldStQuarantine': 'Quarantined',
      'alpha.bridgeCrossSupport': '{pct}% Cross-Support (n={count})',
      'alpha.bridgeEyebrow': 'SHARED GROUND',
      'alpha.budgetSimBreakdownLabel': 'Health: {h}% | Edu: {e}% | Infra: {i}% | Green: {g}%',
      'alpha.budgetSimEyebrow': 'RESOURCE TRADEOFF',
      'alpha.budgetSimProfileBalanced': 'Balanced Allocation',
      'alpha.budgetSimProfileEco': 'Ecological Transition',
      'alpha.budgetSimProfileHuman': 'Human Capital',
      'alpha.budgetSimProfileInfra': 'Infrastructure Growth',
      'alpha.budgetSimUnallocatedLabel': 'Unallocated: {pct}%',
      'alpha.changeMindClassOpen': 'Epistemically Open',
      'alpha.changeMindEyebrow': 'EPISTEMIC FLEXIBILITY',
      'alpha.checklistClose': 'Close',
      'alpha.checklistFullyAudited': 'Fully Audited',
      'alpha.checklistMagicScoreRejected': 'Magic Score Rejected',
      'alpha.checklistMethodologyVerified': 'Methodology Verified',
      'alpha.checklistRevisionNeeded': 'Revision Needed',
      'alpha.checklistSheetTitle': 'Case Quality Audit Checklist',
      'alpha.checklistStatusFlagged': 'Flagged',
      'alpha.checklistStatusPending': 'Pending',
      'alpha.checklistStatusVerified': 'Verified',
      'alpha.citJuryEyebrow': 'CITIZEN JURY',
      'alpha.citJuryStAssembly': 'Stratified Random',
      'alpha.civPetEyebrow': 'CIVIC PETITION',
      'alpha.civPetStSubmitted': 'Parliamentary Hearing',
      'alpha.civicRepoEyebrow': 'CIVIC AUDIT',
      'alpha.civicRepoStAttested': 'Peer-Attested',
      'alpha.civicWorkEyebrow': 'EDUCATION MODE',
      'alpha.civicWorkModFallacy': 'Fallacy',
      'alpha.cogLoadEyebrow': 'ADAPTIVE COGNITIVE',
      'alpha.cogLoadModeStreamlined': 'Streamlined',
      'alpha.consCrcEyebrow': 'MULTI-STAKEHOLDER',
      'alpha.consCrcStRatified': 'Pact Ratified',
      'alpha.contribClassesEligibleBadge': 'Signal Eligible',
      'alpha.contribClassesEyebrow': 'CONTRIBUTION CLASSES',
      'alpha.contribClassesIsolatedBadge': 'Isolated',
      'alpha.contribClassesIsolationBreached': 'Isolation Breached',
      'alpha.contribClassesIsolationEnforced': 'ENFORCED',
      'alpha.contribClassesProofLabel': 'Isolation Proof: {proof}',
      'alpha.contribClassesTitle': 'Pre-Result',
      'alpha.contribClassesTotalLabel': 'Total Contributions: {total}',
      'alpha.correctionNoCorrections': 'No recorded corrections.',
      'alpha.correctionRationaleLabel': 'Rationale:',
      'alpha.correctionSheetTitle': 'Correction',
      'alpha.correctionTypeClarification': 'Clarification',
      'alpha.correctionTypeFactual': 'Factual',
      'alpha.correctionTypeLegal': 'Legal Status Update',
      'alpha.correctionTypeSource': 'Source Expansion',
      'alpha.correctionTypeTypo': 'Typo Fix',
      'alpha.crossSimEyebrow': 'CROSS-CASE SIMILARITY',
      'alpha.crossSimTierHigh': 'High Topological',
      'alpha.cultNormDimSolidarity': 'Community Solidarity',
      'alpha.cultNormEyebrow': 'CROSS-CULTURAL',
      'alpha.delibDepthEyebrow': 'DELIBERATION DEPTH',
      'alpha.delibDepthLevelProfound': 'Profound',
      'alpha.depolarEyebrow': 'DEPOLARIZATION',
      'alpha.depolarStateHigh': 'Convergence',
      'alpha.discProfileAntiAlgorithmNotice': 'No algorithmic manipulation applied; transparent discovery preferences used.',
      'alpha.discProfileComplexityTitle': 'Complexity Preference',
      'alpha.discProfileDiversityBoostDesc': 'Prioritizes diverse perspectives in exploration flow.',
      'alpha.discProfileDiversityBoostTitle': 'Diversity Boost',
      'alpha.discProfileDomainsTitle': 'Interest Domains',
      'alpha.discProfileSaveButton': 'Save Preferences',
      'alpha.discProfileSheetTitle': 'Discovery Profile',
      'alpha.diversityCatAcademic': 'Academic / Scientific',
      'alpha.diversityCatCivic': 'Civic / Independent',
      'alpha.diversityCatGov': 'Official / Government',
      'alpha.diversityCatIndustry': 'Technical / Industry',
      'alpha.diversityCatJournalism': 'Journalism / Media',
      'alpha.diversityEyebrow': 'SOURCE PLURALITY',
      'alpha.diversityLevelBalanced': 'Balanced Diversity',
      'alpha.diversityLevelHigh': 'Pluralism',
      'alpha.diversityLevelLimited': 'Limited Diversity',
      'alpha.driftEyebrow': 'TEMPORAL DRIFT',
      'alpha.driftNatureMatured': 'Matured',
      'alpha.emergencyEyebrow': 'DEMOCRATIC EMERGENCY',
      'alpha.emergencyStProportionate': 'Proportionate & Sunset-Bounded',
      'alpha.encBkpEyebrow': 'E2E ENCRYPTED',
      'alpha.encBkpStSynced': 'Encrypted Vault',
      'alpha.entBoardEyebrow': 'ENTERPRISE & BOARDROOM',
      'alpha.entBoardScopeEsg': 'ESG',
      'alpha.ethVecDomDeontological': 'Deontological',
      'alpha.ethVecEyebrow': 'ETHICAL VECTOR',
      'alpha.evidenceCategoryAcademic': 'Academic',
      'alpha.evidenceStatusExpert': 'Expert',
      'alpha.expertEyebrow': 'EPISTEMIC',
      'alpha.expertGapBridgesTitle': 'Expert Gap Bridges Title',
      'alpha.expertGapClassConvergent': 'Convergent',
      'alpha.expertGapClassNormative': 'Expert Gap Class Normative',
      'alpha.expertGapClassTechnical': 'Expert Gap Class Technical',
      'alpha.expertGapClassTrust': 'Expert Gap Class Trust',
      'alpha.expertGapDriversTitle': 'Expert Gap Drivers Title',
      'alpha.expertGapExpertsSample': 'Expert Sample: n={sample}',
      'alpha.expertGapEyebrow': 'EXPERT-PUBLIC',
      'alpha.expertGapMagnitude': '{points} Points Divergence',
      'alpha.expertGapPublicSample': 'Public Sample: n={sample}',
      'alpha.expertGapTitle': 'Domain Consensus',
      'alpha.expertTierAcademic': 'Peer-Reviewed',
      'alpha.fallacyEyebrow': 'FALLACY',
      'alpha.fallacyTypeStrawMan': 'Straw Man',
      'alpha.fatigueEyebrow': 'HEALTHY PACING',
      'alpha.fatigueStatusOptimal': 'Focused & Optimal',
      'alpha.futureGenEyebrow': 'FUTURE GENERATIONS',
      'alpha.futureGenH100Yr': '100-Year',
      'alpha.futureProxyEyebrow': 'INTERGENERATIONAL JUSTICE',
      'alpha.futureProxyStRegenerative': 'Regenerative 50-Year',
      'alpha.halflifeEyebrow': 'SIGNAL HALF-LIFE',
      'alpha.halflifeStateFresh': 'Fresh',
      'alpha.impactEviEyebrow': 'IMPACT EVIDENCE',
      'alpha.impactEviStatusVerified': 'VERIFIED AUTHENTIC',
      'alpha.impactVerEyebrow': 'COMMUNITY IMPACT',
      'alpha.impactVerVerdictFull': 'Full Resolution',
      'alpha.incentiveMapAlignmentLabel': '{pct}% Alignment',
      'alpha.incentiveMapDriverLabel': 'Primary Driver: {driver}',
      'alpha.incentiveMapEyebrow': 'INCENTIVE MAP',
      'alpha.incentiveMapMitigationLabel': 'Mitigation: {mech}',
      'alpha.incentiveMapRiskLabel': 'Perverse Risk: {risk}',
      'alpha.incentiveMapStatusAligned': 'Aligned',
      'alpha.incentiveMapStatusMisaligned': 'Incentive Map Status Misaligned',
      'alpha.incentiveMapStatusPerverse': 'Incentive Map Status Perverse',
      'alpha.incentiveMapTypeBureaucratic': 'Incentive Map Type Bureaucratic',
      'alpha.incentiveMapTypeCivic': 'Incentive Map Type Civic',
      'alpha.incentiveMapTypeElectoral': 'Incentive Map Type Electoral',
      'alpha.incentiveMapTypeProfit': 'Incentive Map Type Profit',
      'alpha.instRespEyebrow': 'VERIFIED INSTITUTION',
      'alpha.instRespVerifiedBadge': 'OFFICIALLY VERIFIED',
      'alpha.irreversibleClassPerm': 'Permanently',
      'alpha.irreversibleEyebrow': 'REVERSIBILITY',
      'alpha.judicialEyebrow': 'JUDICIAL INDEPENDENCE',
      'alpha.judicialStAligned': 'Precedent-Aligned',
      'alpha.lensPillarLegal': 'Legal',
      'alpha.lensSheetTitle': 'Context',
      'alpha.lobbyRdrEyebrow': 'CONFLICT-OF-INTEREST',
      'alpha.lobbyRdrLvlClean': 'Clean Independent',
      'alpha.mediaScanEyebrow': 'MEDIA MONOPOLY',
      'alpha.mediaScanLvlPluralistic': 'Pluralistic & Independent',
      'alpha.merklePrfEyebrow': 'MERKLE TREE',
      'alpha.merklePrfStInclusion': 'Inclusion Proof',
      'alpha.meshSyncChanBundle': 'Delay-Tolerant',
      'alpha.meshSyncEyebrow': 'LOW-BANDWIDTH',
      'alpha.methodologyClose': 'Close',
      'alpha.methodologyEngine': 'KEFE Verified Methodology Engine {v}',
      'alpha.methodologySafeguardCommitFirst': 'Commit First',
      'alpha.methodologySafeguardNoProfiling': 'No Profiling',
      'alpha.methodologySheetTitle': 'Methodology',
      'alpha.modAuditActionRemove': 'Content Removed',
      'alpha.modAuditEyebrow': 'MODERATION AUDIT',
      'alpha.multiLlmEyebrow': 'CROSS-MODEL MULTI-LLM',
      'alpha.multiLlmLvlUnanimous': 'Unanimous',
      'alpha.multiLocEyebrow': 'MULTILINGUAL',
      'alpha.multiLocTierCertified': 'High-Fidelity',
      'alpha.munBudDomParks': 'Parks',
      'alpha.munBudEyebrow': 'MUNICIPAL & PARTICIPATORY',
      'alpha.ngoDeskDomClimate': 'Environment',
      'alpha.ngoDeskEyebrow': 'CIVIL SOCIETY',
      'alpha.objectionCategoryAmbiguous': 'Ambiguous Options',
      'alpha.objectionCategoryBias': 'Framing',
      'alpha.objectionCategoryDrift': 'Depreciated Context',
      'alpha.objectionCategoryFactual': 'Factual Inaccuracy',
      'alpha.objectionCategoryStakeholder': 'Missing Stakeholder Representation',
      'alpha.objectionDialogTitle': 'Objection',
      'alpha.objectionEvidenceUrlHint': 'Evidence URL link (optional)...',
      'alpha.objectionStatementHint': 'Describe your objection rationale...',
      'alpha.objectionSubmitButton': 'Submit Objection',
      'alpha.observeModeEyebrow': 'OBSERVE MODE',
      'alpha.observeModeModeObserve': 'Observe Only',
      'alpha.observeModeModeStudy': 'Study and Learn',
      'alpha.observeModeModeTransition': 'Transition to Weigh',
      'alpha.observeModeNonBindingBadge': 'NON-BINDING',
      'alpha.observeModeStatsLabel': '{args} Arguments, {ev} Evidence Reviewed',
      'alpha.perspSpecEyebrow': 'PERSPECTIVE SPECTRUM',
      'alpha.perspSpecValEquality': 'Equality',
      'alpha.policySimEyebrow': 'POLICY SIMULATOR',
      'alpha.policySimKnobLabel': '{knob}: {val}%',
      'alpha.policySimScoresLabel': 'Fiscal: {f}% | Social: {s}% | Eco: {e}%',
      'alpha.policySimStateDeficit': 'High Deficit Risk',
      'alpha.policySimStateEnv': 'Environmental Degradation Risk',
      'alpha.policySimStateOptimal': 'Optimal',
      'alpha.policySimStateSocial': 'Severe Social Impact Risk',
      'alpha.principleEyebrow': 'PRINCIPLE-FIRST',
      'alpha.principleTypeLiberty': 'Individual Liberty',
      'alpha.privBudEyebrow': 'DIFFERENTIAL PRIVACY',
      'alpha.privBudStHealthy': 'Privacy Budget Healthy',
      'alpha.processAnalysisCompleted': 'Completed',
      'alpha.processAnalysisCurrentStage': 'Current Stage: {stage}',
      'alpha.processAnalysisDays': '{days} Days',
      'alpha.processAnalysisEyebrow': 'PROCESS ANALYSIS',
      'alpha.processAnalysisIntegrityLabel': '{pct}% Process Integrity',
      'alpha.processAnalysisOversightLabel': 'Oversight Body: {body}',
      'alpha.procureEyebrow': 'PUBLIC PROCUREMENT',
      'alpha.procureLvlOpen': 'Open Competitive',
      'alpha.promMtxEyebrow': 'INSTITUTIONAL PROMISE',
      'alpha.promMtxStDelivered': 'Promise Delivered',
      'alpha.proportionalEyebrow': 'PROPORTIONALITY',
      'alpha.proportionalOutcomeValid': 'Constitutionally Valid',
      'alpha.rebuttalEyebrow': 'DIALECTICAL',
      'alpha.rebuttalTypeEmpirical': 'Empirical',
      'alpha.receiptEyebrow': 'CRYPTOGRAPHIC DECISION',
      'alpha.receiptVerifiedBadge': 'SEALED',
      'alpha.respAnalysisClarityLabel': '{pct}% Responsibility Clarity',
      'alpha.respAnalysisDutyEthical': 'Fiduciary & Ethical Duty',
      'alpha.respAnalysisDutyExecution': 'Operational Execution',
      'alpha.respAnalysisDutyLegal': 'Legal Liability',
      'alpha.respAnalysisDutyOversight': 'Regulatory Oversight',
      'alpha.respAnalysisEyebrow': 'RESPONSIBILITY',
      'alpha.respAnalysisGapWarning': 'Responsibility gap detected.',
      'alpha.respAnalysisRedressLabel': 'Legal Redress: {ch}',
      'alpha.retroSimEraCentury20': '20th-Century',
      'alpha.retroSimEyebrow': 'HISTORICAL RETROSPECTIVE',
      'alpha.revolveEyebrow': 'REVOLVING DOOR',
      'alpha.revolveStCompliant': 'Cooling-Off',
      'alpha.rightsEyebrow': 'FUNDAMENTAL RIGHTS',
      'alpha.rightsSevPermissible': 'Permissible',
      'alpha.roleFlipEyebrow': 'ROLE FLIP',
      'alpha.roleFlipInitialLabel': 'Your Initial Perspective',
      'alpha.segmentDistEntropyLabel': 'Entropy Score: {entropy}',
      'alpha.segmentDistEyebrow': 'PRIVACY-SAFE',
      'alpha.segmentDistOverallSample': 'Total Sample: n={sample}',
      'alpha.segmentDistPrimaryPref': 'Primary Preference: {choice}',
      'alpha.segmentDistPrivacyBadge': 'Differential Privacy (k >= {k})',
      'alpha.segmentDistSuppressedNotice': 'Suppressed to protect anonymity (below {threshold})',
      'alpha.segmentDistTitle': 'Cohort Perspective',
      'alpha.segmentDistTypeAge': 'Age Cohort',
      'alpha.segmentDistTypeExperience': 'Experience Level',
      'alpha.segmentDistTypeRegional': 'Regional Cohort',
      'alpha.segmentDistTypeStakeholder': 'Stakeholder Role',
      'alpha.segmentDistTypeUrbanRural': 'Urban / Rural Cohort',
      'alpha.sessDevEyebrow': 'SESSION & ACTIVE',
      'alpha.sessDevTierHardware': 'Hardware Keystore',
      'alpha.sigHealthClose': 'Close',
      'alpha.sigHealthEyebrow': 'SIGNAL HEALTH AUDIT',
      'alpha.sigHealthFlagged': 'Flagged',
      'alpha.sigHealthMethodologyVerified': 'Methodology Verified: {h}',
      'alpha.sigHealthNotice': 'Signal health monitors manipulation and bias metrics.',
      'alpha.sigHealthPassed': 'PASSED',
      'alpha.sigHealthSampleLabel': 'Sample: n={sample}',
      'alpha.sigHealthScoreLabel': 'Health Score: {score}%',
      'alpha.sigHealthStNoise': 'Noise / Low Quality',
      'alpha.sigHealthStProvisional': 'Provisional Signal',
      'alpha.sigHealthStQualified': 'QUALIFIED CIVIC SIGNAL',
      'alpha.sigScopeDimensionInvalid': 'INVALID BOUNDARY',
      'alpha.sigScopeDimensionValid': 'VALID BOUNDARY',
      'alpha.sigScopeEyebrow': 'SIGNAL SCOPE ALIGNMENT',
      'alpha.sigScopeGeoLabel': 'Geographic Scope: {geo}',
      'alpha.sigScopeJurisdictionLabel': 'Jurisdiction: {jur}',
      'alpha.sigScopeNotice': 'Scope alignment preserves target audience and jurisdiction boundaries.',
      'alpha.sigScopePopulationLabel': 'Target Population: {pop}',
      'alpha.sigScopeScoreLabel': 'Scope Alignment: {score}%',
      'alpha.sigScopeSealVerified': 'Scope Seal Verified: {seal}',
      'alpha.sigScopeStAligned': 'STRICTLY ALIGNED',
      'alpha.sigScopeStDisqualified': 'Out of Scope / Disqualified',
      'alpha.sigScopeStOverbroad': 'Overbroad Warning',
      'alpha.sigScopeTitle': 'Signal Scope and Jurisdiction Alignment',
      'alpha.sigScopeValidityLabel': 'Validity Window: {days} Days',
      'alpha.sigTargetChannelLabel': 'Contact Channel: {ch}',
      'alpha.sigTargetEyebrow': 'SIGNAL TARGET REGISTRY',
      'alpha.sigTargetNotice': 'Target registry contains verified official authorities.',
      'alpha.sigTargetPrimaryBadge': 'PRIMARY TARGET',
      'alpha.sigTargetProofVerified': 'Registry Proof Verified: {proof}',
      'alpha.sigTargetResponseDue': 'Response Due: {days} Days',
      'alpha.sigTargetSecondaryBadge': 'Secondary Target',
      'alpha.sigTargetStAcknowledged': 'OFFICIALLY ACKNOWLEDGED',
      'alpha.sigTargetStDeclined': 'Declined Jurisdiction',
      'alpha.sigTargetStDispatched': 'Dispatched to Target',
      'alpha.sigTargetStPledged': 'Action Pledged',
      'alpha.sigTargetStProposed': 'Proposed Target',
      'alpha.sigTargetStVerified': 'Verified Target',
      'alpha.sigTargetTitle': 'Institutional and Regulatory Target Authorities',
      'alpha.sigVersChainInvalid': 'Audit Chain Invalid',
      'alpha.sigVersChainVerified': 'CHAIN INTEGRITY VERIFIED',
      'alpha.sigVersCurrentVersionLabel': 'Active: {v}',
      'alpha.sigVersDeltaConfidenceLabel': 'Confidence Delta: {conf}%',
      'alpha.sigVersDeltaShiftLabel': '{shift}% Distribution Shift',
      'alpha.sigVersDeltaTitle': 'Version Shift Analysis',
      'alpha.sigVersEyebrow': 'SIGNAL VERSIONING',
      'alpha.sigVersGenesis': 'Genesis Version',
      'alpha.sigVersNotice': 'Signal versions snapshot consensus dynamics over time.',
      'alpha.sigVersParentHash': 'Parent Snapshot: {hash}',
      'alpha.sigVersSnapshotSample': 'Sample: n={s} | Confidence: {c}%',
      'alpha.sigVersTitle': 'Signal Versioning & Shift Tracking',
      'alpha.signalQualAuditHashLabel': 'Audit Hash: {hash}',
      'alpha.signalQualChannelsTitle': 'Verification Channels',
      'alpha.signalQualEyebrow': 'METHODOLOGY-QUALIFIED SIGNAL',
      'alpha.signalQualSampleLabel': 'Sample: n={sample}',
      'alpha.signalQualScoreLabel': '{score}% Signal Qualification',
      'alpha.signalQualStatusDisqualified': 'Disqualified',
      'alpha.signalQualStatusProvisional': 'Provisional Qualification',
      'alpha.signalQualStatusQualified': 'Fully Qualified',
      'alpha.signalQualTierBronze': 'Bronze Qualification',
      'alpha.signalQualTierGold': 'Gold Standard Signal',
      'alpha.signalQualTierSilver': 'Silver Qualification',
      'alpha.signalQualTierUnqualified': 'Unqualified Tier',
      'alpha.signalQualTitle': 'Signal Qualification Matrix',
      'alpha.sovereigntyEyebrow': 'DIGITAL SOVEREIGNTY',
      'alpha.sovereigntyStEnforced': 'Sovereign Local Residency',
      'alpha.stakeholderDistCohesionLabel': 'Cohesion Index: {c}',
      'alpha.stakeholderDistDivergenceNegative': '-{pts} Divergence',
      'alpha.stakeholderDistDivergencePositive': '+{pts} Divergence',
      'alpha.stakeholderDistEyebrow': 'MULTI-STAKEHOLDER',
      'alpha.stakeholderDistPluralismScore': 'Pluralism Score: {score}',
      'alpha.stakeholderDistRoleCivic': 'Civic Community',
      'alpha.stakeholderDistRoleCommercial': 'Commercial Enterprises',
      'alpha.stakeholderDistRoleDirectlyImpacted': 'Directly Impacted',
      'alpha.stakeholderDistRoleFrontline': 'Frontline Practitioners',
      'alpha.stakeholderDistRoleRegulatory': 'Regulatory Oversight',
      'alpha.stakeholderDistTitle': 'Deliberation Topology',
      'alpha.stakeholderDistTotalRepresented': '{count} Stakeholders Represented',
      'alpha.stakeholderEyebrow': 'STAKEHOLDER',
      'alpha.stakeholderMatrixEyebrow': 'STAKEHOLDER IMPACT',
      'alpha.stakeholderMatrixNetScore': '+{score} Net Equity Score',
      'alpha.stakeholderSampleInfo': 'n={sample}',
      'alpha.stakeholderTitle': 'different groups',
      'alpha.sysHealthEyebrow': 'SERVICE HEALTH',
      'alpha.sysHealthStOptimal': 'Operational',
      'alpha.tempFlowEpochInitial': 'Blind First',
      'alpha.tempFlowEyebrow': 'TEMPORAL OPINION',
      'alpha.thresholdEyebrow': 'THRESHOLD',
      'alpha.thresholdTippingPoint': 'Critical Tipping Point: {val} {unit}',
      'alpha.treeBranchEyebrow': 'DECISION TREE',
      'alpha.treeBranchNodeFork': 'Primary Policy',
      'alpha.triangleArchetypeRights': 'Rights',
      'alpha.triangleEyebrow': 'TRIANGLE',
      'alpha.trustStandEyebrow': 'COMMUNITY TRUST',
      'alpha.trustStandTierExemplary': 'Exemplary Civic',
      'alpha.ugcPropEyebrow': 'COMMUNITY DILEMMA',
      'alpha.ugcPropNeutralityLabel': '{score}% Neutrality Score',
      'alpha.ugcPropStateApproved': 'Editorial Approved',
      'alpha.ugcPropStateDraft': 'Draft Submitted',
      'alpha.ugcPropStateRejected': 'Rejected with Reason',
      'alpha.ugcPropStateReview': 'Peer Review',
      'alpha.ugcPropSupportersLabel': '{count} Supporters',
      'alpha.unintendedEyebrow': 'UNINTENDED CONSEQUENCES',
      'alpha.unintendedTypePerverse': 'Perverse Incentive',
      'alpha.vulnerableCohortDisability': 'Disabilities',
      'alpha.vulnerableEyebrow': 'VULNERABLE GROUPS',
      'alpha.xaiProvEyebrow': 'XAI REASONING',
      'alpha.xaiProvTierAxiomatic': 'Full Axiomatic',
      'alpha.youthSpaceEyebrow': 'YOUTH & STUDENT',
      'alpha.youthSpaceFocusCampus': 'Campus',
    },
    'tr': {
      'primary_nav.explore': 'Keşfet',
      'primary_nav.weigh': 'Tartım',
      'primary_nav.activity': 'Aktivite',
      'primary_nav.my_kefe': 'My KEFE',
      'account.title': 'Hesabını koru',
      'account.heading': 'Tartımların seninle gelsin.',
      'account.body':
          'Hesap isteğe bağlıdır. Misafir olarak devam edebilirsin; hesap açarsan mevcut geçmişin sunucuda aynı kimliğe bağlanır.',
      'account.email': 'E-posta',
      'account.phone': 'Telefon',
      'account.email_address': 'E-posta adresi',
      'account.phone_number': 'Telefon numarası',
      'account.send_code': 'Doğrulama kodu gönder',
      'account.code_instruction':
          '{destination} adresine gönderilen 6 haneli kodu gir.',
      'account.verification_code': 'Doğrulama kodu',
      'account.convert': 'Hesaba dönüştür',
      'account.merged':
          'Hesabın doğrulandı ve iki geçmiş güvenli biçimde birleştirildi.',
      'account.preserved':
          'Hesabın doğrulandı. Mevcut tartım geçmişin korunuyor.',
      'account.return_my_kefe': 'My KEFE’ye dön',
      'account.protect_action': 'Geçmişimi koru',
      'account.failure': 'İşlem tamamlanamadı · {code}',
      'account.error_otp_invalid':
          'Doğrulama kodu hatalı. Lütfen kodu kontrol edip tekrar dene.',
      'account.error_otp_expired':
          'Doğrulama kodunun süresi doldu. Lütfen yeni bir kod iste.',
      'account.error_otp_locked':
          'Çok fazla deneme yapıldı. Lütfen daha sonra tekrar dene veya yeni bir kod iste.',
      'account.error_challenge_expired':
          'Doğrulama oturumunun süresi doldu. Lütfen yeni bir kod iste.',
      'account.error_merge_failed':
          'Hesap geçmişi birleştirilemedi. Lütfen yeni bir doğrulama kodu iste.',
      'account.error_delivery_unavailable':
          'Doğrulama kodu iletimi geçici olarak kullanılamıyor. Lütfen daha sonra tekrar dene.',
      'account.error_generic':
          'Doğrulama işlemi tamamlanamadı. Lütfen tekrar dene.',
      'account.restart_challenge': 'Hedefi değiştir veya yeni kod iste',
      'activity.eyebrow': 'AKTİVİTE',
      'activity.title': 'Kararlarına geri dön.',
      'activity.subtitle':
          'Kaydettiğin vakalar, geçmiş kararların ve yeniden tartım izlerin burada birbirinden ayrı görünür.',
      'activity.loading': 'Aktiviten yükleniyor…',
      'activity.unavailable': 'Aktivite şu anda yüklenemedi.',
      'activity.retry': 'Tekrar dene',
      'activity.empty':
          'Henüz geçmiş bir tartımın yok. İlk kararından sonra burada görünecek.',
      'activity.history_title': 'Karar geçmişin',
      'activity.committed': 'Karar verildi',
      'activity.reflected': 'Yansıma tamamlandı',
      'activity.update_count.one': '{count} yeniden tartım',
      'activity.update_count.many': '{count} yeniden tartım',
      'activity.preview_notice':
          'Bu ekrandaki karar geçmişi Product Preview örnek verisidir; canlı kullanıcı verisi değildir.',
      'weigh_hub.eyebrow': 'TARTIM',
      'weigh_hub.title': 'Sıradaki kararını seç.',
      'weigh_hub.subtitle':
          'Önce kendi kararını ver; topluluk sonucu yalnız Commit sonrasında açılır.',
      'weigh_hub.recommended': 'ÖNERİLEN TARTIM',
      'weigh_hub.start': 'Tartıma başla',
      'weigh_hub.more': 'Diğer tartımlar',
      'weigh_hub.empty': 'Şu anda tartıma açık bir vaka yok.',
      'privacy.title': 'Gizlilik ve veriler',
      'privacy.heading': 'Verilerin ve gizliliğin',
      'privacy.body':
          'Kendi ürün geçmişinin makine-okunur kopyasını alabilir veya hesabındaki/misafir kimliğindeki özel verileri silebilirsin.',
      'privacy.export_ready': 'Veri kopyan hazır',
      'privacy.export_copied':
          'Makine-okunur JSON panoya kopyalandı. Güvenlik tokenları ve başka kullanıcıların verileri bu dışa aktarıma dahil değildir.',
      'privacy.export_summary_title': 'Bu kopyaya dahil olanlar',
      'privacy.export_record_count.one': '{count} kayıt dahil',
      'privacy.export_record_count.many': '{count} kayıt dahil',
      'privacy.export_group_count.one': '1 veri grubunda kayıt var',
      'privacy.export_group_count.many': '{count} veri grubunda kayıt var',
      'privacy.done': 'Tamam',
      'privacy.export': 'Verilerimi dışa aktar',
      'privacy.delete': 'Verilerimi sil',
      'privacy.failure': 'Gizlilik işlemi başarısız · {code}',
      'privacy.delete_title': 'Verileri kalıcı olarak sil?',
      'privacy.delete_body':
          'Bu işlem geri alınamaz. Devam etmek için DELETE yaz.',
      'privacy.cancel': 'Vazgeç',
      'privacy.delete_permanently': 'Kalıcı olarak sil',
      'privacy.delete_complete_title': 'Verilerin silindi',
      'privacy.delete_complete_body':
          'Bu kimliğe bağlı özel ürün verileri silindi. Toplu katkılar anonimleştirildi.',
      'privacy.delete_preview_complete_title': 'Önizleme verileri sıfırlandı',
      'privacy.delete_preview_complete_body':
          'Product Preview örnek verileri sıfırlandı. Hiçbir üretim hesabı veya canlı veri silinmedi.',
      'privacy.delete_continue': 'Devam et',
      'share.title': 'Bu vakayı paylaş',
      'share.case_only_note':
          'MVP paylaşımı yalnız vakayı içerir. Kararın, güven puanın ve özel gerekçen bağlantıya eklenmez.',
      'share.preparing': 'Bağlantı hazırlanıyor…',
      'share.create': 'Vaka bağlantısı oluştur',
      'share.copied': 'Bağlantı kopyalandı.',
      'share.copy': 'Kopyala',
      'share.revoke': 'Bağlantıyı iptal et',
      'share.failure': 'Paylaşım oluşturulamadı · {code}',
      'public_share.unavailable': 'Bu paylaşım artık kullanılamıyor.',
      'public_share.retry': 'Tekrar dene',
      'public_share.eyebrow': 'Bir KEFE vakası paylaşıldı',
      'public_share.blind_first':
          'Paylaşan kişinin kararı burada gösterilmez. Önce aynı vakayı kendin tart ve kararını sabitle; topluluk sonucu ancak kendi Commit’inden sonra açılır.',
      'public_share.weigh': 'Ben de tartayım',
      'community.title': 'Topluluk gerekçeleri',
      'community.private_note':
          'Özel gerekçen burada otomatik yayınlanmaz. Topluluğa katkı ayrı bir eylemdir; metinli katkılar moderasyondan geçer.',
      'community.publish_heading': 'Sen de ayrı bir gerekçe yayınla',
      'community.optional_text': 'İsteğe bağlı kısa metin',
      'community.moderation_note':
          'Metin varsa yayınlanmadan önce moderasyon bekler.',
      'community.submitting': 'Gönderiliyor…',
      'community.publish': 'Topluluğa yayınla',
      'community.receipt_pending':
          'Katkın alındı. Metin moderasyon sonrası görünür olabilir.',
      'community.receipt_allowed': 'Katkın topluluk gerekçelerine eklendi.',
      'community.unavailable': 'Topluluk verisi kullanılamıyor · {code}',
      'community.patterns_eyebrow': 'BETİMLEYİCİ ÖRÜNTÜLER',
      'community.patterns_title': 'Yayınlanan gerekçelerde neler öne çıktı',
      'community.patterns_sample': 'Yayınlanmış {count} gerekçede',
      'community.patterns_value': '{count} / {sample}',
      'community.patterns_semantics':
          '{label}: yayınlanmış {sample} gerekçenin {count} tanesinde',
      'community.patterns_note':
          "Bir katkı birden fazla etiket taşıyabilir; bu yüzden satırlar %100'e tamamlanmaz. Bu yalnız betimleyicidir; popülerlik veya doğruluk sıralaması değildir.",
      'community.published': 'Yayınlanan gerekçeler',
      'community.resonates': 'Bende yankılandı',
      'community.useful': 'Faydalı',
      'community.report': 'Raporla',
      'consensus.loading': 'Konsensüs kartı hazırlanıyor…',
      'consensus.commit_first': 'Önce kararını sabitle',
      'consensus.commit_first_body':
          'Konsensüs katılımı yalnız tamamlanmış bir tartımdan sonra açılır.',
      'consensus.retry': 'Tekrar dene',
      'consensus.exposed': 'EXPOSED · Ana sonuç örneklemine dahil değil',
      'consensus.prompt':
          'Bu ifadeye ne kadar katılıyorsun? Kartın dağılımı kendi yanıtından sonra açılır.',
      'consensus.reason_limit': 'Gerekçeni en fazla {max} etiketle belirt',
      'consensus.submitting': 'Katılım kaydediliyor…',
      'consensus.join': 'Sen de Katıl',
      'consensus.exposed_methodology':
          'Bu katılım, kararını verdikten sonra gerçekleştiği için EXPOSED olarak tutulur. Ana sonuç veya Signal değildir.',
      'consensus.distribution': 'KONSENSÜS DAĞILIMI',
      'consensus.reason_patterns': 'GEREKÇE ÖRÜNTÜLERİ',
      'consensus.eyebrow': 'WE · ORTAK ZEMİN',
      'consensus.card_title': 'Konsensüs Kartı',
      'consensus.unavailable': 'Konsensüs geçici olarak kullanılamıyor',
      'consensus.unavailable_with_code':
          'Konsensüs geçici olarak kullanılamıyor · {code}',
      'consensus.stance.agree': 'Katılıyorum',
      'consensus.stance.mixed': 'Kısmen',
      'consensus.stance.disagree': 'Katılmıyorum',
      'consensus.reason.fairness': 'Adalet',
      'consensus.reason.need': 'İhtiyaç',
      'consensus.reason.rules': 'Kurallar',
      'consensus.reason.practical_impact': 'Pratik etki',
      'consensus.reason.responsibility': 'Sorumluluk',
      'domain.daily_life': 'Günlük yaşam',
      'domain.technology': 'Teknoloji',
      'domain.sports': 'Spor',
      'domain.civic': 'Kamusal',
      'domain.work_economy': 'İş & Ekonomi',
      'domain.education': 'Eğitim',
      'domain.family_parenting': 'Aile & Ebeveynlik',
      'domain.culture_media': 'Kültür & Medya',
      'context.event_summary': 'Olay özeti',
      'context.information_status': 'Bilgi durumu',
      'journey.label': 'KARAR YOLCULUĞU',
      'step.case': 'Olay',
      'step.weigh': 'Tartım',
      'step.result': 'Sonuç',
      'step.reflection': 'Yansıma',
      'step.completed': 'Tamamlandı',
      'result.eyebrow': 'SONUÇLAR',
      'result.your_decision': 'SENİN KARARIN',
      'result.community_distribution': 'TOPLULUK DAĞILIMI',
      'result.kefe_gap': 'KEFE UÇURUMU',
      'result.gap.top':
          'Seçimin toplulukta en yüksek paya sahip. Katılımcıların %{percent} kadarı aynı seçeneği tercih etti.',
      'result.gap.not_top':
          'Seçtiğin seçenek toplulukta çoğunluk değil. Katılımcıların %{percent} kadarı aynı seçeneği tercih etti.',
      'result.gap.difference':
          'Seçtiğin seçenek toplulukta %{selectedPercent}. En yüksek paya sahip seçenekle fark {gapPoints} yüzde puan.',
      'result.decision_you': 'Sen',
      'result.balance_no_selection': 'Henüz seçim yok',
      'result.balance_semantics': 'KEFE terazisi. {selectedLabel}',
      'result.methodology': '{trustedSample} · n={sampleSize} · {confidence}',
      'confidence.high': 'Yüksek güven',
      'confidence.medium': 'Orta güven',
      'confidence.low': 'Düşük güven',
      'perspective.eyebrow': 'KARŞI GÖRÜŞLER',
      'question.confidence': 'EMİNLİK',
      'question.decision': 'KARAR',
      'decision.opt_out_insufficient_info': 'Yeterli bilgim yok / Bilmiyorum',
      'decision.opt_out_missing_options': 'Seçenekler eksik / Farklı bir durum var',
      'decision.opt_out_title': 'ALTERNATİF YANITLAR',
      'reasons.eyebrow': 'GEREKÇELER',
      'alpha.acadPortCorpGraph': 'Argüman Grafı',
      'alpha.acadPortEyebrow': 'AKADEMİK ARAŞTIRMA',
      'alpha.accVoiceEyebrow': 'ERİŞİLEBİLİR SESLİ',
      'alpha.accVoiceModeDictation': 'Anonimleştirilmiş',
      'alpha.actionEvidenceButton': 'Kanıtı İncele',
      'alpha.actionEyebrow': 'EYLEM',
      'alpha.actionProgressLabel': '%{pct} İlerleme',
      'alpha.actionStatusInProgress': 'Devam',
      'alpha.actionStatusProposed': 'Önerildi',
      'alpha.actionStatusStalled': 'Duraklatıldı',
      'alpha.actionStatusVerifiedComplete': 'Doğrulanmış Tamamlandı',
      'alpha.actionTargetDate': 'Hedef: {date}',
      'alpha.actionTrackEyebrow': 'KURUM EYLEM',
      'alpha.actionTrackStatusProgress': 'Uygulamada',
      'alpha.agendaThrEyebrow': 'DİNAMİK GÜNDEM',
      'alpha.agendaThrTierNational': 'Ulusal Aciliyet',
      'alpha.aiAuditEyebrow': 'YAPAY ZEKA HALÜSİNASYON',
      'alpha.aiAuditStGrounded': 'Olgusal Temellendirilmiş',
      'alpha.aiFacEyebrow': 'TARAFSIZLIK GÜVENCELİ',
      'alpha.aiFacModeSocratic': 'Sokratik Sorgulama',
      'alpha.anatomyDriverNormative': 'Ahlaki',
      'alpha.anatomyEyebrow': 'ANATOMİSİ',
      'alpha.appealPanelEyebrow': 'TOPLULUK İTİRAZ',
      'alpha.appealPanelVerdictOverturned': 'Karar Bozuldu',
      'alpha.argClusteringArchetypeAlternative': 'Alternatif Paradigma',
      'alpha.argClusteringArchetypeBridge': 'Ortak Zemin',
      'alpha.argClusteringArchetypeNearConsensus': 'Geniş Mutabakat',
      'alpha.argClusteringArchetypeOpposing': 'Karşıt İlke',
      'alpha.argClusteringEyebrow': 'ARGÜMAN KALIP',
      'alpha.argClusteringTotalArgs': '{total} Argüman Kümelendi',
      'alpha.argStrengthEyebrow': 'ARGÜMAN GÜCÜ',
      'alpha.argStrengthTierRobust': 'Kademe A',
      'alpha.blindEyebrow': 'KÖR/TARAFSIZ',
      'alpha.blindModeActor': 'Aktör Körlemesi',
      'alpha.botShieldEyebrow': 'SENTETİK ASTROTURFING',
      'alpha.botShieldStQuarantine': 'Karantinaya Alındı',
      'alpha.bridgeCrossSupport': '%{pct} Çapraz Destek (n={count})',
      'alpha.bridgeEyebrow': 'ORTAK ZEMİN',
      'alpha.budgetSimBreakdownLabel': 'Sağlık: %{h} | Eğitim: %{e} | Altyapı: %{i} | Yeşil: %{g}',
      'alpha.budgetSimEyebrow': 'KAYNAK DEĞİŞ-TOKUŞ',
      'alpha.budgetSimProfileBalanced': 'Dengeli Dağılım',
      'alpha.budgetSimProfileEco': 'Ekolojik Dönüşüm',
      'alpha.budgetSimProfileHuman': 'İnsani Sermaye',
      'alpha.budgetSimProfileInfra': 'Altyapı Büyümesi',
      'alpha.budgetSimUnallocatedLabel': 'Ayrılmamış: %{pct}',
      'alpha.changeMindClassOpen': 'Yüksek Epistemik Esneklik',
      'alpha.changeMindEyebrow': 'FİKRİMİ NE DEĞİŞTİRİRDİ',
      'alpha.checklistClose': 'Kapat',
      'alpha.checklistFullyAudited': 'Tamamen Denetlendi',
      'alpha.checklistMagicScoreRejected': 'Sihirli Skor Reddedildi',
      'alpha.checklistMethodologyVerified': 'Metodoloji Doğrulandı',
      'alpha.checklistRevisionNeeded': 'Revizyon Gerekli',
      'alpha.checklistSheetTitle': 'Vaka Kalite Denetim Listesi',
      'alpha.checklistStatusFlagged': 'İŞARETLENDİ',
      'alpha.checklistStatusPending': 'BEKLEMEDE',
      'alpha.checklistStatusVerified': 'DOĞRULANDI',
      'alpha.citJuryEyebrow': 'YURTTAŞ KARAR HEYETİ',
      'alpha.citJuryStAssembly': 'Tabakalı Rastlantısal',
      'alpha.civPetEyebrow': 'SİVİL DİLEKÇE',
      'alpha.civPetStSubmitted': 'Meclis Komisyon',
      'alpha.civicRepoEyebrow': 'YURTTAŞ DENETİM',
      'alpha.civicRepoStAttested': 'Hakem Onaylı',
      'alpha.civicWorkEyebrow': 'EĞİTİM MODU',
      'alpha.civicWorkModFallacy': 'Safsata',
      'alpha.cogLoadEyebrow': 'BİLİŞSEL YÜK',
      'alpha.cogLoadModeStreamlined': 'Yalınlaştırılmış',
      'alpha.consCrcEyebrow': 'ÇOKLU PAYDAŞLI',
      'alpha.consCrcStRatified': 'Sözleşmesi Onaylandı',
      'alpha.contribClassesEligibleBadge': 'Sinyale Uygun',
      'alpha.contribClassesEyebrow': 'KATKI SINIFLARI AYRIŞTIRMASI',
      'alpha.contribClassesIsolatedBadge': 'İzole Edildi',
      'alpha.contribClassesIsolationBreached': 'İzolasyon İhlali',
      'alpha.contribClassesIsolationEnforced': 'AKTİF',
      'alpha.contribClassesProofLabel': 'İzolasyon Kanıtı: {proof}',
      'alpha.contribClassesTitle': 'Körleme Öncesi',
      'alpha.contribClassesTotalLabel': 'Toplam Katkı: {total}',
      'alpha.correctionNoCorrections': 'Kayıtlı düzeltme bulunmuyor.',
      'alpha.correctionRationaleLabel': 'Gerekçe:',
      'alpha.correctionSheetTitle': 'Düzeltme',
      'alpha.correctionTypeClarification': 'Açıklama',
      'alpha.correctionTypeFactual': 'Olgusal',
      'alpha.correctionTypeLegal': 'Hukuki Durum Güncellemesi',
      'alpha.correctionTypeSource': 'Kaynak Genişletme',
      'alpha.correctionTypeTypo': 'Yazım Düzeltmesi',
      'alpha.crossSimEyebrow': 'ÇAPRAZ VAKA KARŞILAŞTIRMA',
      'alpha.crossSimTierHigh': 'Yüksek Topolojik',
      'alpha.cultNormDimSolidarity': 'Toplumsal Dayanışma',
      'alpha.cultNormEyebrow': 'ÇAPRAZ KÜLTÜREL',
      'alpha.delibDepthEyebrow': 'MÜZAKERE DERİNLİĞİ',
      'alpha.delibDepthLevelProfound': 'Derinlemesine',
      'alpha.depolarEyebrow': 'KUTUPLAŞMA AZALTMA',
      'alpha.depolarStateHigh': 'Yakınlaşma',
      'alpha.discProfileAntiAlgorithmNotice': 'Algoritmik yönlendirme uygulanmaz; şeffaf keşif tercihleri kullanılır.',
      'alpha.discProfileComplexityTitle': 'Karmaşıklık Tercihi',
      'alpha.discProfileDiversityBoostDesc': 'Farklı bakış açılarını keşif akışında öne çıkarır.',
      'alpha.discProfileDiversityBoostTitle': 'Çoğulculuk Desteği',
      'alpha.discProfileDomainsTitle': 'İlgi Alanları',
      'alpha.discProfileSaveButton': 'Keşif Tercihlerini Kaydet',
      'alpha.discProfileSheetTitle': 'Keşif ve Gündem Tercihleri',
      'alpha.diversityCatAcademic': 'Akademik / Bilimsel',
      'alpha.diversityCatCivic': 'Sivil / Bağımsız',
      'alpha.diversityCatGov': 'Resmi / Kamu',
      'alpha.diversityCatIndustry': 'Teknik / Endüstri',
      'alpha.diversityCatJournalism': 'Gazetecilik / Medya',
      'alpha.diversityEyebrow': 'KAYNAK ÇEŞİTLİLİĞİ',
      'alpha.diversityLevelBalanced': 'Dengeli Çeşitlilik',
      'alpha.diversityLevelHigh': 'Yüksek Çeşitlilik ve Çoğulcu Yapı',
      'alpha.diversityLevelLimited': 'Sınırlı Çeşitlilik',
      'alpha.driftEyebrow': 'ZAMANSAL FİKİR',
      'alpha.driftNatureMatured': 'Olgunlaşmış',
      'alpha.emergencyEyebrow': 'OLAĞANÜSTÜ HAL',
      'alpha.emergencyStProportionate': 'Ölçülü ve Süre Sınırlı',
      'alpha.encBkpEyebrow': 'UÇTAN UCA ŞİFRELİ',
      'alpha.encBkpStSynced': 'Şifreli Kasaya',
      'alpha.entBoardEyebrow': 'KURUMSAL YÖNETİM KURULU',
      'alpha.entBoardScopeEsg': 'ESG',
      'alpha.ethVecDomDeontological': 'Ödev',
      'alpha.ethVecEyebrow': 'ETİK HARİTALAMA',
      'alpha.evidenceCategoryAcademic': 'Akademik',
      'alpha.evidenceStatusExpert': 'Uzman',
      'alpha.expertEyebrow': 'EPİSTEMİK',
      'alpha.expertGapBridgesTitle': 'Expert Gap Bridges Başlığı',
      'alpha.expertGapClassConvergent': 'Ortak Mutabakat',
      'alpha.expertGapClassNormative': 'Değer ve Ahlaki Öncelik',
      'alpha.expertGapClassTechnical': 'Expert Gap Class Technical',
      'alpha.expertGapClassTrust': 'Expert Gap Class Trust',
      'alpha.expertGapDriversTitle': 'Expert Gap Drivers Başlığı',
      'alpha.expertGapExpertsSample': 'Uzman Örneklemi: n={sample}',
      'alpha.expertGapEyebrow': 'UZMAN-KAMU',
      'alpha.expertGapMagnitude': '%{points} Ayrışma Büyüklüğü',
      'alpha.expertGapPublicSample': 'Toplum Örneklemi: n={sample}',
      'alpha.expertGapTitle': 'Uzman Mutabakatı',
      'alpha.expertTierAcademic': 'Bağımsız',
      'alpha.fallacyEyebrow': 'SAFSATA',
      'alpha.fallacyTypeStrawMan': 'Korkuluk',
      'alpha.fatigueEyebrow': 'SAĞLIKLI RİTİM',
      'alpha.fatigueStatusOptimal': 'Odaklanmış ve Dengeli',
      'alpha.futureGenEyebrow': 'GELECEK KUŞAKLAR',
      'alpha.futureGenH100Yr': '100 Yıllık',
      'alpha.futureProxyEyebrow': 'GELECEK NESİLLER',
      'alpha.futureProxyStRegenerative': 'Yenileyici Gezegen Emaneti',
      'alpha.halflifeEyebrow': 'SİNYAL YARI ÖMRÜ',
      'alpha.halflifeStateFresh': 'Taze',
      'alpha.impactEviEyebrow': 'SOMUT ETKİ KANITI',
      'alpha.impactEviStatusVerified': 'DOĞRULANMIŞ ÖZGÜN',
      'alpha.impactVerEyebrow': 'TOPLULUK ETKİ',
      'alpha.impactVerVerdictFull': 'Tam Çözüm',
      'alpha.incentiveMapAlignmentLabel': '%{pct} Uyum Oranı',
      'alpha.incentiveMapDriverLabel': 'Birincil İtici Güç: {driver}',
      'alpha.incentiveMapEyebrow': 'TEŞVİK HARİTASI',
      'alpha.incentiveMapMitigationLabel': 'Risk Azaltma: {mech}',
      'alpha.incentiveMapRiskLabel': 'Ters Teşvik Riski: {risk}',
      'alpha.incentiveMapStatusAligned': 'Uyumlu',
      'alpha.incentiveMapStatusMisaligned': 'Incentive Map Durumu Misaligned',
      'alpha.incentiveMapStatusPerverse': 'Incentive Map Durumu Perverse',
      'alpha.incentiveMapTypeBureaucratic': 'Incentive Map Türü Bureaucratic',
      'alpha.incentiveMapTypeCivic': 'Incentive Map Türü Sivil',
      'alpha.incentiveMapTypeElectoral': 'Incentive Map Türü Electoral',
      'alpha.incentiveMapTypeProfit': 'Incentive Map Türü Profit',
      'alpha.instRespEyebrow': 'DOĞRULANMIŞ KURUM',
      'alpha.instRespVerifiedBadge': 'RESMİ DOĞRULANMIŞ',
      'alpha.irreversibleClassPerm': 'Kalıcı ve Geri',
      'alpha.irreversibleEyebrow': 'GERİ DÖNÜŞ',
      'alpha.judicialEyebrow': 'YARGI BAĞIMSIZLIĞI',
      'alpha.judicialStAligned': 'İçtihatla Uyumlu',
      'alpha.lensPillarLegal': 'Hukuki',
      'alpha.lensSheetTitle': 'Bağlam',
      'alpha.lobbyRdrEyebrow': 'ÇIKAR ÇATIŞMASI',
      'alpha.lobbyRdrLvlClean': 'Temiz Bağımsız',
      'alpha.mediaScanEyebrow': 'MEDYA TEKELLEŞMESİ',
      'alpha.mediaScanLvlPluralistic': 'Çoğulcu ve Bağımsız',
      'alpha.merklePrfEyebrow': 'MERKLE AĞACI',
      'alpha.merklePrfStInclusion': 'Kriptografik Ağaç',
      'alpha.meshSyncChanBundle': 'Gecikmeye Dayanıklı',
      'alpha.meshSyncEyebrow': 'DÜŞÜK BANT',
      'alpha.methodologyClose': 'Kapat',
      'alpha.methodologyEngine': 'KEFE Doğrulanmış Metodoloji Motoru {v}',
      'alpha.methodologySafeguardCommitFirst': 'Commit First',
      'alpha.methodologySafeguardNoProfiling': 'Profilleme Yapılmaz',
      'alpha.methodologySheetTitle': 'Metodoloji',
      'alpha.modAuditActionRemove': 'İçerik Kaldırıldı',
      'alpha.modAuditEyebrow': 'MODERASYON DENETİM',
      'alpha.multiLlmEyebrow': 'ÇAPRAZ MODEL ÇOKLU LLM',
      'alpha.multiLlmLvlUnanimous': 'Oybirliğiyle',
      'alpha.multiLocEyebrow': 'ÇOK DİLLİ',
      'alpha.multiLocTierCertified': 'Yüksek Doğruluklu',
      'alpha.munBudDomParks': 'Parklar',
      'alpha.munBudEyebrow': 'YEREL YÖNETİM',
      'alpha.ngoDeskDomClimate': 'Çevre',
      'alpha.ngoDeskEyebrow': 'SİVİL TOPLUM',
      'alpha.objectionCategoryAmbiguous': 'Muğlak Seçenekler',
      'alpha.objectionCategoryBias': 'Çerçeveleme',
      'alpha.objectionCategoryDrift': 'Bağlam Kayması',
      'alpha.objectionCategoryFactual': 'Maddi Olgu Hatası',
      'alpha.objectionCategoryStakeholder': 'Eksik Paydaş Temsili',
      'alpha.objectionDialogTitle': 'İtiraz',
      'alpha.objectionEvidenceUrlHint': 'Kanıt URL bağlantısı (isteğe bağlı)...',
      'alpha.objectionStatementHint': 'İtiraz gerekçenizi açıklayınız...',
      'alpha.objectionSubmitButton': 'İtirazı Gönder',
      'alpha.observeModeEyebrow': 'GÖZLEMCİ MODU',
      'alpha.observeModeModeObserve': 'Yalnızca İncele',
      'alpha.observeModeModeStudy': 'İncele ve Öğren',
      'alpha.observeModeModeTransition': 'Tartıma Geç',
      'alpha.observeModeNonBindingBadge': 'BAĞLAYICI',
      'alpha.observeModeStatsLabel': '{args} Argüman, {ev} Kanıt İncelendi',
      'alpha.perspSpecEyebrow': 'PERSPEKTİF TAYFI',
      'alpha.perspSpecValEquality': 'Eşitlik',
      'alpha.policySimEyebrow': 'POLİTİKA SİMÜLATÖRÜ',
      'alpha.policySimKnobLabel': '{knob}: %{val}',
      'alpha.policySimScoresLabel': 'Mali: %{f} | Sosyal: %{s} | Çevre: %{e}',
      'alpha.policySimStateDeficit': 'Yüksek Bütçe Açığı Riski',
      'alpha.policySimStateEnv': 'Çevresel Bozulma Riski',
      'alpha.policySimStateOptimal': 'Optimal',
      'alpha.policySimStateSocial': 'Ağır Sosyal Etki Riski',
      'alpha.principleEyebrow': 'İLKELER ÖNCELİKLİ',
      'alpha.principleTypeLiberty': 'Bireysel Özgürlük',
      'alpha.privBudEyebrow': 'DİFERANSİYEL GİZLİLİK',
      'alpha.privBudStHealthy': 'Gizlilik Bütçesi Sağlıklı',
      'alpha.processAnalysisCompleted': 'Tamamlandı',
      'alpha.processAnalysisCurrentStage': 'Mevcut Aşama: {stage}',
      'alpha.processAnalysisDays': '{days} Gün',
      'alpha.processAnalysisEyebrow': 'SÜREÇ ANALİZİ',
      'alpha.processAnalysisIntegrityLabel': '%{pct} Süreç Bütünlüğü',
      'alpha.processAnalysisOversightLabel': 'Denetim Organı: {body}',
      'alpha.procureEyebrow': 'KAMU İHALE VE KAYNAK',
      'alpha.procureLvlOpen': 'Açık Rekabetçi',
      'alpha.promMtxEyebrow': 'KURUMSAL VAAT',
      'alpha.promMtxStDelivered': 'Vaat Tamamlandı',
      'alpha.proportionalEyebrow': 'ÖLÇÜLÜLÜK',
      'alpha.proportionalOutcomeValid': 'Hukuken Geçerli',
      'alpha.rebuttalEyebrow': 'DİYALEKTİK',
      'alpha.rebuttalTypeEmpirical': 'Doğrudan Olgusal',
      'alpha.receiptEyebrow': 'KRİPTOGRAFİK KARAR',
      'alpha.receiptVerifiedBadge': 'MÜHÜRLENDİ',
      'alpha.respAnalysisClarityLabel': '%{pct} Sorumluluk Netliği',
      'alpha.respAnalysisDutyEthical': 'Güven ve Etik Sorumluluk',
      'alpha.respAnalysisDutyExecution': 'Operasyonel İcra',
      'alpha.respAnalysisDutyLegal': 'Hukuki Sorumluluk',
      'alpha.respAnalysisDutyOversight': 'Düzenleyici Denetim',
      'alpha.respAnalysisEyebrow': 'SORUMLULUK',
      'alpha.respAnalysisGapWarning': 'Sorumluluk boşluğu tespit edildi.',
      'alpha.respAnalysisRedressLabel': 'Yasal Başvuru / İtiraz: {ch}',
      'alpha.retroSimEraCentury20': '20. Yüzyıl',
      'alpha.retroSimEyebrow': 'TARİHSEL KARAR',
      'alpha.revolveEyebrow': 'DÖNER KAPI',
      'alpha.revolveStCompliant': 'Soğuma Süresine',
      'alpha.rightsEyebrow': 'TEMEL HAKLAR',
      'alpha.rightsSevPermissible': 'Ölçülü',
      'alpha.roleFlipEyebrow': 'ROL DEĞİŞİMİ',
      'alpha.roleFlipInitialLabel': 'Başlangıç Bakış Açınız',
      'alpha.segmentDistEntropyLabel': 'Entropi Skoru: {entropy}',
      'alpha.segmentDistEyebrow': 'GİZLİLİK KORUMALI',
      'alpha.segmentDistOverallSample': 'Toplam Örneklem: n={sample}',
      'alpha.segmentDistPrimaryPref': 'Birincil Tercih: {choice}',
      'alpha.segmentDistPrivacyBadge': 'Diferansiyel Gizlilik (k >= {k})',
      'alpha.segmentDistSuppressedNotice': 'Anonimliği korumak için gizlendi ({threshold} altı)',
      'alpha.segmentDistTitle': 'Toplumsal Kesim',
      'alpha.segmentDistTypeAge': 'Yaş Grubu',
      'alpha.segmentDistTypeExperience': 'Deneyim Seviyesi',
      'alpha.segmentDistTypeRegional': 'Bölgesel Grup',
      'alpha.segmentDistTypeStakeholder': 'Paydaş Rolü',
      'alpha.segmentDistTypeUrbanRural': 'Kentsel / Kırsal Dağılım',
      'alpha.sessDevEyebrow': 'OTURUM VE AKTİF',
      'alpha.sessDevTierHardware': 'Donanım Anahtar',
      'alpha.sigHealthClose': 'Kapat',
      'alpha.sigHealthEyebrow': 'SİNYAL SAĞLIK DENETİMİ',
      'alpha.sigHealthFlagged': 'İşaretlendi',
      'alpha.sigHealthMethodologyVerified': 'Metodoloji Doğrulandı: {h}',
      'alpha.sigHealthNotice': 'Sinyal sağlığı manipülasyon ve yanlılık metriklerini izler.',
      'alpha.sigHealthPassed': 'GEÇTİ',
      'alpha.sigHealthSampleLabel': 'Örneklem: n={sample}',
      'alpha.sigHealthScoreLabel': 'Sağlık Skoru: %{score}',
      'alpha.sigHealthStNoise': 'Gürültü / Düşük Kalite',
      'alpha.sigHealthStProvisional': 'Geçici Sinyal',
      'alpha.sigHealthStQualified': 'NİTELİKLİ YURTTAŞLIK SİNYALİ',
      'alpha.sigScopeDimensionInvalid': 'GEÇERSİZ SINIR',
      'alpha.sigScopeDimensionValid': 'GEÇERLİ SINIR',
      'alpha.sigScopeEyebrow': 'SİNYAL KAPSAM UYUMU',
      'alpha.sigScopeGeoLabel': 'Coğrafi Kapsam: {geo}',
      'alpha.sigScopeJurisdictionLabel': 'Yetki Alanı: {jur}',
      'alpha.sigScopeNotice': 'Kapsam uyumu hedef kitle ve yetki sınırlarını korur.',
      'alpha.sigScopePopulationLabel': 'Hedef Kitle: {pop}',
      'alpha.sigScopeScoreLabel': 'Kapsam Uyumu: %{score}',
      'alpha.sigScopeSealVerified': 'Kapsam Mührü Doğrulandı: {seal}',
      'alpha.sigScopeStAligned': 'KESİN UYUMLU',
      'alpha.sigScopeStDisqualified': 'Kapsam Dışı / Diskalifiye',
      'alpha.sigScopeStOverbroad': 'Aşırı Geniş Kapsam Uyarısı',
      'alpha.sigScopeTitle': 'Sinyal Kapsamı ve Yetki Alanı Uyumu',
      'alpha.sigScopeValidityLabel': 'Geçerlilik Penceresi: {days} Gün',
      'alpha.sigTargetChannelLabel': 'İletişim Kanalı: {ch}',
      'alpha.sigTargetEyebrow': 'SİNYAL HEDEF KAYIT DEFTERİ',
      'alpha.sigTargetNotice': 'Hedef muhatap sicili doğrulanmış resmi mercileri içerir.',
      'alpha.sigTargetPrimaryBadge': 'BİRİNCİL HEDEF',
      'alpha.sigTargetProofVerified': 'Sicil Kanıtı Doğrulandı: {proof}',
      'alpha.sigTargetResponseDue': 'Cevap Süresi: {days} Gün',
      'alpha.sigTargetSecondaryBadge': 'İkincil Muhatap',
      'alpha.sigTargetStAcknowledged': 'RESMİ ALINDI ONAYI',
      'alpha.sigTargetStDeclined': 'Yetki Alanı Dışı / Reddedildi',
      'alpha.sigTargetStDispatched': 'Muhataba İletildi',
      'alpha.sigTargetStPledged': 'Eylem Taahhüdü Alındı',
      'alpha.sigTargetStProposed': 'Önerilen Muhatap',
      'alpha.sigTargetStVerified': 'Doğrulanmış Muhatap',
      'alpha.sigTargetTitle': 'Kurumsal ve Düzenleyici Hedef Merciler',
      'alpha.sigVersChainInvalid': 'Denetim Zinciri Geçersiz',
      'alpha.sigVersChainVerified': 'ZİNCİR BÜTÜNLÜĞÜ DOĞRULANDI',
      'alpha.sigVersCurrentVersionLabel': 'Aktif: {v}',
      'alpha.sigVersDeltaConfidenceLabel': 'Güvenilirlik Artışı: +%{conf}',
      'alpha.sigVersDeltaShiftLabel': 'Dağılım Farkı: %{shift}',
      'alpha.sigVersDeltaTitle': 'Metodoloji Güncelleme Farkı',
      'alpha.sigVersEyebrow': 'SİNYAL SÜRÜMLENDİRME VE DENETİM ZİNCİRİ',
      'alpha.sigVersGenesis': 'Başlangıç Sürümü (Genesis)',
      'alpha.sigVersNotice': 'Sinyal sürümleri zaman içindeki uzlaşı dinamiklerini dondurur.',
      'alpha.sigVersParentHash': 'Üst Snapshot: {hash}',
      'alpha.sigVersSnapshotSample': 'Örneklem: n={s} | Güven: %{c}',
      'alpha.sigVersTitle': 'Metodoloji Sürümüne Bağlı Sinyal Geçmişi',
      'alpha.signalQualAuditHashLabel': 'Denetim Özeti: {hash}',
      'alpha.signalQualChannelsTitle': 'Doğrulama Kanalları',
      'alpha.signalQualEyebrow': 'METODOLOJİK DOĞRULANMIŞ SİNYAL',
      'alpha.signalQualSampleLabel': 'Örneklem: n={sample}',
      'alpha.signalQualScoreLabel': '%{score} Sinyal Yeterliliği',
      'alpha.signalQualStatusDisqualified': 'Yetersiz / Diskalifiye',
      'alpha.signalQualStatusProvisional': 'Geçici Yeterlilik',
      'alpha.signalQualStatusQualified': 'Tam Yeterlilik',
      'alpha.signalQualTierBronze': 'Bronz Yeterlilik',
      'alpha.signalQualTierGold': 'Altın Standart Sinyal',
      'alpha.signalQualTierSilver': 'Gümüş Yeterlilik',
      'alpha.signalQualTierUnqualified': 'Yetersiz Seviye',
      'alpha.signalQualTitle': 'Sinyal Nitelik Matrisi',
      'alpha.sovereigntyEyebrow': 'DİJİTAL EGEMENLİK',
      'alpha.sovereigntyStEnforced': 'Kriptografik Yerel Egemenlik',
      'alpha.stakeholderDistCohesionLabel': 'Uyum İndeksi: {c}',
      'alpha.stakeholderDistDivergenceNegative': '-%{pts} Ayrışma',
      'alpha.stakeholderDistDivergencePositive': '+%{pts} Ayrışma',
      'alpha.stakeholderDistEyebrow': 'ÇOK PAYDAŞLI',
      'alpha.stakeholderDistPluralismScore': 'Çoğulculuk Skoru: {score}',
      'alpha.stakeholderDistRoleCivic': 'Sivil Toplum',
      'alpha.stakeholderDistRoleCommercial': 'Ticari İşletmeler',
      'alpha.stakeholderDistRoleDirectlyImpacted': 'Doğrudan',
      'alpha.stakeholderDistRoleFrontline': 'Saha Uygulayıcıları',
      'alpha.stakeholderDistRoleRegulatory': 'Düzenleyici Otorite',
      'alpha.stakeholderDistTitle': 'Müzakere Topolojisi',
      'alpha.stakeholderDistTotalRepresented': '{count} Paydaş Temsil Edildi',
      'alpha.stakeholderEyebrow': 'PAYDAŞ',
      'alpha.stakeholderMatrixEyebrow': 'PAYDAŞ ETKİ',
      'alpha.stakeholderMatrixNetScore': '+{score} Net Eşitlik Skoru',
      'alpha.stakeholderSampleInfo': 'n={sample}',
      'alpha.stakeholderTitle': 'nasıl tarttı',
      'alpha.sysHealthEyebrow': 'SİSTEM DURUMU',
      'alpha.sysHealthStOptimal': 'Tüm Sistemler',
      'alpha.tempFlowEpochInitial': 'Kör Tartım',
      'alpha.tempFlowEyebrow': 'ZAMAN BOYUTLU FİKİR',
      'alpha.thresholdEyebrow': 'EŞİK',
      'alpha.thresholdTippingPoint': 'Kritik Eşik Noktası: {val} {unit}',
      'alpha.treeBranchEyebrow': 'KARAR AĞACI',
      'alpha.treeBranchNodeFork': 'Ana Politika',
      'alpha.triangleArchetypeRights': 'Kural',
      'alpha.triangleEyebrow': 'ÜÇGENİ',
      'alpha.trustStandEyebrow': 'TOPLULUK GÜVEN',
      'alpha.trustStandTierExemplary': 'Örnek Sivil',
      'alpha.ugcPropEyebrow': 'TOPLULUK İKİLEM',
      'alpha.ugcPropNeutralityLabel': '%{score} Tarafsızlık Skoru',
      'alpha.ugcPropStateApproved': 'Editoryal Onaylandı',
      'alpha.ugcPropStateDraft': 'Taslak Gönderildi',
      'alpha.ugcPropStateRejected': 'Gerekçeli Reddedildi',
      'alpha.ugcPropStateReview': 'Hakem',
      'alpha.ugcPropSupportersLabel': '{count} Destekçi',
      'alpha.unintendedEyebrow': 'BEKLENMEYEN SONUÇLAR',
      'alpha.unintendedTypePerverse': 'Tersine Teşvik',
      'alpha.vulnerableCohortDisability': 'Engelli',
      'alpha.vulnerableEyebrow': 'KIRILGAN GRUPLAR',
      'alpha.xaiProvEyebrow': 'AÇIKLANABİLİR YAPAY ZEKA',
      'alpha.xaiProvTierAxiomatic': 'Aksiyomatik Köken',
      'alpha.youthSpaceEyebrow': 'GENÇLİK VE ÖĞRENCİ',
      'alpha.youthSpaceFocusCampus': 'Kampüs',
    },
  };
}
