import 'kefe_locale_catalog.dart';

abstract final class InternalAlphaStringCatalog {
  static const KefeLocaleResources resources = {
    'en': {
      'primary_nav.explore': 'Explore',
      'primary_nav.weigh': 'Weigh',
      'primary_nav.activity': 'Activity',
      'primary_nav.my_kefe': 'My KEFE',
      'account.title': 'Protect your history',
      'account.heading': 'Keep your weighs with you.',
      'account.body': 'An account is optional. You can stay a guest; converting preserves your existing server history under the same identity.',
      'account.email': 'Email',
      'account.phone': 'Phone',
      'account.email_address': 'Email address',
      'account.phone_number': 'Phone number',
      'account.send_code': 'Send verification code',
      'account.code_instruction': 'Enter the 6-digit code sent to {destination}.',
      'account.verification_code': 'Verification code',
      'account.convert': 'Convert account',
      'account.merged': 'Account verified and both histories were safely merged.',
      'account.preserved': 'Account verified. Your existing weigh history is preserved.',
      'account.return_my_kefe': 'Return to My KEFE',
      'account.protect_action': 'Protect my history',
      'account.failure': 'Could not complete · {code}',
      'activity.eyebrow': 'ACTIVITY',
      'activity.title': 'Return to your decisions.',
      'activity.subtitle': 'Saved Cases, past decisions and revisit history stay distinct here.',
      'activity.loading': 'Loading your activity…',
      'activity.unavailable': 'Activity is currently unavailable.',
      'activity.retry': 'Retry',
      'activity.empty': 'You have no past weighs yet. They will appear after your first decision.',
      'activity.history_title': 'Decision history',
      'activity.committed': 'Decision committed',
      'activity.reflected': 'Reflection completed',
      'activity.update_count.one': '{count} decision update',
      'activity.update_count.many': '{count} decision updates',
      'activity.preview_notice': 'Decision history on this screen is Product Preview sample data, not live user data.',
      'weigh_hub.eyebrow': 'WEIGH',
      'weigh_hub.title': 'Choose your next decision.',
      'weigh_hub.subtitle': 'Decide first; collective results unlock only after Commit.',
      'weigh_hub.recommended': 'RECOMMENDED WEIGH',
      'weigh_hub.start': 'Start weighing',
      'weigh_hub.more': 'More Cases',
      'weigh_hub.empty': 'No Cases are currently open for weighing.',
      'privacy.title': 'Privacy and data',
      'privacy.heading': 'Your data and privacy',
      'privacy.body': 'Export a machine-readable copy of your product history or delete private data attached to your account/guest identity.',
      'privacy.export_ready': 'Your data copy is ready',
      'privacy.export_copied': 'Machine-readable JSON was copied to the clipboard. Security tokens and other users’ data are excluded.',
      'privacy.done': 'Done',
      'privacy.export': 'Export my data',
      'privacy.delete': 'Delete my data',
      'privacy.failure': 'Privacy action failed · {code}',
      'privacy.delete_title': 'Delete data permanently?',
      'privacy.delete_body': 'This cannot be undone. Type DELETE to continue.',
      'privacy.cancel': 'Cancel',
      'privacy.delete_permanently': 'Delete permanently',
      'share.title': 'Share this case',
      'share.case_only_note': 'MVP sharing is case-only. Your decision, confidence, and private reason are never included in the link.',
      'share.preparing': 'Preparing link…',
      'share.create': 'Create case link',
      'share.copied': 'Link copied.',
      'share.copy': 'Copy',
      'share.revoke': 'Revoke link',
      'share.failure': 'Share failed · {code}',
      'public_share.unavailable': 'This share is no longer available.',
      'public_share.retry': 'Try again',
      'public_share.eyebrow': 'A KEFE case was shared',
      'public_share.blind_first': "The sender’s decision is never shown here. Weigh the same case and Commit first; collective results unlock only after your own Commit.",
      'public_share.weigh': 'Weigh it myself',
      'community.title': 'Community reasons',
      'community.private_note': 'Your private reason is never published here automatically. Community contribution is a separate action; text contributions are moderated.',
      'community.publish_heading': 'Publish a separate reason',
      'community.optional_text': 'Optional short text',
      'community.moderation_note': 'Text waits for moderation before public display.',
      'community.submitting': 'Submitting…',
      'community.publish': 'Publish to community',
      'community.receipt_pending': 'Contribution received. Text may become visible after moderation.',
      'community.receipt_allowed': 'Your contribution was added to Community Reasons.',
      'community.unavailable': 'Community data unavailable · {code}',
      'community.published': 'Published reasons',
      'community.resonates': 'Resonates',
      'community.useful': 'Useful',
      'community.report': 'Report',
      'consensus.loading': 'Preparing consensus card…',
      'consensus.commit_first': 'Commit your decision first',
      'consensus.commit_first_body': 'Consensus participation unlocks only after a completed weigh.',
      'consensus.retry': 'Retry',
      'consensus.exposed': 'EXPOSED · Not part of the core result sample',
      'consensus.prompt': 'How much do you agree? This card’s distribution unlocks after your own response.',
      'consensus.reason_limit': 'Choose up to {max} reason tags',
      'consensus.submitting': 'Submitting…',
      'consensus.join': 'Join the consensus',
      'consensus.exposed_methodology': 'Because this happens after your decision, it is stored as EXPOSED. It is not the core result or a Signal.',
      'consensus.distribution': 'CONSENSUS DISTRIBUTION',
      'consensus.reason_patterns': 'REASON PATTERNS',
      'consensus.eyebrow': 'WE · COMMON GROUND',
      'consensus.card_title': 'Consensus Card',
      'consensus.unavailable': 'Consensus temporarily unavailable',
      'consensus.unavailable_with_code': 'Consensus temporarily unavailable · {code}',
      'consensus.stance.agree': 'Agree',
      'consensus.stance.mixed': 'Mixed',
      'consensus.stance.disagree': 'Disagree',
      'consensus.reason.fairness': 'Fairness',
      'consensus.reason.need': 'Need',
      'consensus.reason.rules': 'Rules',
      'consensus.reason.practical_impact': 'Practical impact',
      'consensus.reason.responsibility': 'Responsibility',
      'domain.daily_life': 'Daily life',
      'domain.technology': 'Technology',
      'domain.sports': 'Sports',
      'domain.civic': 'Civic',
      'domain.work_economy': 'Work & Economy',
      'domain.education': 'Education',
      'domain.family_parenting': 'Family & Parenting',
      'domain.culture_media': 'Culture & Media',
      'context.event_summary': 'Event summary',
      'context.information_status': 'Information status',
      'journey.label': 'DECISION JOURNEY',
      'step.case': 'Case',
      'step.weigh': 'Weigh',
      'step.result': 'Result',
      'step.reflection': 'Reflection',
      'step.completed': 'Completed',
      'result.eyebrow': 'RESULTS',
      'result.your_decision': 'YOUR DECISION',
      'result.community_distribution': 'COMMUNITY DISTRIBUTION',
      'result.kefe_gap': 'KEFE GAP',
      'result.gap.top': 'Your choice has the largest share in the community. {percent}% of participants chose the same option.',
      'result.gap.not_top': 'Your choice is not the community majority. {percent}% of participants chose the same option.',
      'result.gap.difference': 'Your choice has {selectedPercent}% of the community. The gap to the leading option is {gapPoints} percentage points.',
      'result.decision_you': 'You',
      'result.balance_no_selection': 'No selection yet',
      'result.balance_semantics': 'KEFE balance. {selectedLabel}',
      'result.methodology': '{trustedSample} · n={sampleSize} · {confidence}',
      'confidence.high': 'High confidence',
      'confidence.medium': 'Medium confidence',
      'confidence.low': 'Low confidence',
      'perspective.eyebrow': 'COUNTER VIEWS',
      'question.confidence': 'CONFIDENCE',
      'question.decision': 'DECISION',
      'reasons.eyebrow': 'REASONS',
    },
    'tr': {
      'primary_nav.explore': 'Keşfet',
      'primary_nav.weigh': 'Tartım',
      'primary_nav.activity': 'Aktivite',
      'primary_nav.my_kefe': 'My KEFE',
      'account.title': 'Hesabını koru',
      'account.heading': 'Tartımların seninle gelsin.',
      'account.body': 'Hesap isteğe bağlıdır. Misafir olarak devam edebilirsin; hesap açarsan mevcut geçmişin sunucuda aynı kimliğe bağlanır.',
      'account.email': 'E-posta',
      'account.phone': 'Telefon',
      'account.email_address': 'E-posta adresi',
      'account.phone_number': 'Telefon numarası',
      'account.send_code': 'Doğrulama kodu gönder',
      'account.code_instruction': '{destination} adresine gönderilen 6 haneli kodu gir.',
      'account.verification_code': 'Doğrulama kodu',
      'account.convert': 'Hesaba dönüştür',
      'account.merged': 'Hesabın doğrulandı ve iki geçmiş güvenli biçimde birleştirildi.',
      'account.preserved': 'Hesabın doğrulandı. Mevcut tartım geçmişin korunuyor.',
      'account.return_my_kefe': 'My KEFE’ye dön',
      'account.protect_action': 'Geçmişimi koru',
      'account.failure': 'İşlem tamamlanamadı · {code}',
      'activity.eyebrow': 'AKTİVİTE',
      'activity.title': 'Kararlarına geri dön.',
      'activity.subtitle': 'Kaydettiğin vakalar, geçmiş kararların ve yeniden tartım izlerin burada birbirinden ayrı görünür.',
      'activity.loading': 'Aktiviten yükleniyor…',
      'activity.unavailable': 'Aktivite şu anda yüklenemedi.',
      'activity.retry': 'Tekrar dene',
      'activity.empty': 'Henüz geçmiş bir tartımın yok. İlk kararından sonra burada görünecek.',
      'activity.history_title': 'Karar geçmişin',
      'activity.committed': 'Karar verildi',
      'activity.reflected': 'Yansıma tamamlandı',
      'activity.update_count.one': '{count} yeniden tartım',
      'activity.update_count.many': '{count} yeniden tartım',
      'activity.preview_notice': 'Bu ekrandaki karar geçmişi Product Preview örnek verisidir; canlı kullanıcı verisi değildir.',
      'weigh_hub.eyebrow': 'TARTIM',
      'weigh_hub.title': 'Sıradaki kararını seç.',
      'weigh_hub.subtitle': 'Önce kendi kararını ver; topluluk sonucu yalnız Commit sonrasında açılır.',
      'weigh_hub.recommended': 'ÖNERİLEN TARTIM',
      'weigh_hub.start': 'Tartıma başla',
      'weigh_hub.more': 'Diğer tartımlar',
      'weigh_hub.empty': 'Şu anda tartıma açık bir vaka yok.',
      'privacy.title': 'Gizlilik ve veriler',
      'privacy.heading': 'Verilerin ve gizliliğin',
      'privacy.body': 'Kendi ürün geçmişinin makine-okunur kopyasını alabilir veya hesabındaki/misafir kimliğindeki özel verileri silebilirsin.',
      'privacy.export_ready': 'Veri kopyan hazır',
      'privacy.export_copied': 'Makine-okunur JSON panoya kopyalandı. Güvenlik tokenları ve başka kullanıcıların verileri bu dışa aktarıma dahil değildir.',
      'privacy.done': 'Tamam',
      'privacy.export': 'Verilerimi dışa aktar',
      'privacy.delete': 'Verilerimi sil',
      'privacy.failure': 'Gizlilik işlemi başarısız · {code}',
      'privacy.delete_title': 'Verileri kalıcı olarak sil?',
      'privacy.delete_body': 'Bu işlem geri alınamaz. Devam etmek için DELETE yaz.',
      'privacy.cancel': 'Vazgeç',
      'privacy.delete_permanently': 'Kalıcı olarak sil',
      'share.title': 'Bu vakayı paylaş',
      'share.case_only_note': 'MVP paylaşımı yalnız vakayı içerir. Kararın, güven puanın ve özel gerekçen bağlantıya eklenmez.',
      'share.preparing': 'Bağlantı hazırlanıyor…',
      'share.create': 'Vaka bağlantısı oluştur',
      'share.copied': 'Bağlantı kopyalandı.',
      'share.copy': 'Kopyala',
      'share.revoke': 'Bağlantıyı iptal et',
      'share.failure': 'Paylaşım oluşturulamadı · {code}',
      'public_share.unavailable': 'Bu paylaşım artık kullanılamıyor.',
      'public_share.retry': 'Tekrar dene',
      'public_share.eyebrow': 'Bir KEFE vakası paylaşıldı',
      'public_share.blind_first': 'Paylaşan kişinin kararı burada gösterilmez. Önce aynı vakayı kendin tart ve kararını sabitle; topluluk sonucu ancak kendi Commit’inden sonra açılır.',
      'public_share.weigh': 'Ben de tartayım',
      'community.title': 'Topluluk gerekçeleri',
      'community.private_note': 'Özel gerekçen burada otomatik yayınlanmaz. Topluluğa katkı ayrı bir eylemdir; metinli katkılar moderasyondan geçer.',
      'community.publish_heading': 'Sen de ayrı bir gerekçe yayınla',
      'community.optional_text': 'İsteğe bağlı kısa metin',
      'community.moderation_note': 'Metin varsa yayınlanmadan önce moderasyon bekler.',
      'community.submitting': 'Gönderiliyor…',
      'community.publish': 'Topluluğa yayınla',
      'community.receipt_pending': 'Katkın alındı. Metin moderasyon sonrası görünür olabilir.',
      'community.receipt_allowed': 'Katkın topluluk gerekçelerine eklendi.',
      'community.unavailable': 'Topluluk verisi kullanılamıyor · {code}',
      'community.published': 'Yayınlanan gerekçeler',
      'community.resonates': 'Bende yankılandı',
      'community.useful': 'Faydalı',
      'community.report': 'Raporla',
      'consensus.loading': 'Konsensüs kartı hazırlanıyor…',
      'consensus.commit_first': 'Önce kararını sabitle',
      'consensus.commit_first_body': 'Konsensüs katılımı yalnız tamamlanmış bir tartımdan sonra açılır.',
      'consensus.retry': 'Tekrar dene',
      'consensus.exposed': 'EXPOSED · Ana sonuç örneklemine dahil değil',
      'consensus.prompt': 'Bu ifadeye ne kadar katılıyorsun? Kartın dağılımı kendi yanıtından sonra açılır.',
      'consensus.reason_limit': 'Gerekçeni en fazla {max} etiketle belirt',
      'consensus.submitting': 'Katılım kaydediliyor…',
      'consensus.join': 'Sen de Katıl',
      'consensus.exposed_methodology': 'Bu katılım, kararını verdikten sonra gerçekleştiği için EXPOSED olarak tutulur. Ana sonuç veya Signal değildir.',
      'consensus.distribution': 'KONSENSÜS DAĞILIMI',
      'consensus.reason_patterns': 'GEREKÇE ÖRÜNTÜLERİ',
      'consensus.eyebrow': 'WE · ORTAK ZEMİN',
      'consensus.card_title': 'Konsensüs Kartı',
      'consensus.unavailable': 'Konsensüs geçici olarak kullanılamıyor',
      'consensus.unavailable_with_code': 'Konsensüs geçici olarak kullanılamıyor · {code}',
      'consensus.stance.agree': 'Katılıyorum',
      'consensus.stance.mixed': 'Kısmen',
      'consensus.stance.disagree': 'Katılmıyorum',
      'consensus.reason.fairness': 'Adalet',
      'consensus.reason.need': 'İhtiyaç',
      'consensus.reason.rules': 'Kurallar',
      'consensus.reason.practical_impact': 'Pratik etki',
      'consensus.reason.responsibility': 'Sorumluluk',
      'domain.daily_life': 'Günlük yaşam',
      'domain.technology': 'Teknoloji',
      'domain.sports': 'Spor',
      'domain.civic': 'Kamusal',
      'domain.work_economy': 'İş & Ekonomi',
      'domain.education': 'Eğitim',
      'domain.family_parenting': 'Aile & Ebeveynlik',
      'domain.culture_media': 'Kültür & Medya',
      'context.event_summary': 'Olay özeti',
      'context.information_status': 'Bilgi durumu',
      'journey.label': 'KARAR YOLCULUĞU',
      'step.case': 'Olay',
      'step.weigh': 'Tartım',
      'step.result': 'Sonuç',
      'step.reflection': 'Yansıma',
      'step.completed': 'Tamamlandı',
      'result.eyebrow': 'SONUÇLAR',
      'result.your_decision': 'SENİN KARARIN',
      'result.community_distribution': 'TOPLULUK DAĞILIMI',
      'result.kefe_gap': 'KEFE UÇURUMU',
      'result.gap.top': 'Seçimin toplulukta en yüksek paya sahip. Katılımcıların %{percent} kadarı aynı seçeneği tercih etti.',
      'result.gap.not_top': 'Seçtiğin seçenek toplulukta çoğunluk değil. Katılımcıların %{percent} kadarı aynı seçeneği tercih etti.',
      'result.gap.difference': 'Seçtiğin seçenek toplulukta %{selectedPercent}. En yüksek paya sahip seçenekle fark {gapPoints} yüzde puan.',
      'result.decision_you': 'Sen',
      'result.balance_no_selection': 'Henüz seçim yok',
      'result.balance_semantics': 'KEFE terazisi. {selectedLabel}',
      'result.methodology': '{trustedSample} · n={sampleSize} · {confidence}',
      'confidence.high': 'Yüksek güven',
      'confidence.medium': 'Orta güven',
      'confidence.low': 'Düşük güven',
      'perspective.eyebrow': 'KARŞI GÖRÜŞLER',
      'question.confidence': 'EMİNLİK',
      'question.decision': 'KARAR',
      'reasons.eyebrow': 'GEREKÇELER',
    },
  };
}
